### ISSUE TITLE
GitLab API: Get all files from each branch (Question)

### ISSUE THREAD

**Issue by kenokenobingo** [jdalrymple/node-gitlab#112]
Using `node-gitlab`, I’d like to get the files of all branches for each repository via the GitLab API. So far my code in Vue.js looks like this: https://pastebin.com/8RC7sxgG. How can I accomplish this?

**Comment by jdalrymple** [comment]
Hmm. You only want the files corresponding to the branches? not tags?

Assuming just branches I would:

1. First get and go over all the projects like you've done,
2. Then for each project, get its corresponding branches
3. I would use the repository API to get the files tree
4. Then loop through this tree (or run each request in parallel) to get each specific file using the repository files API

Its pretty verbose of a process lol, but it could definitely be sped up if you filter some of the calls. i.e using the `simple` options when getting the projects so the request takes much less time, same with the branches request.

**Comment by kenokenobingo** [comment]
Thanks, that’s really helped a lot!
