### ISSUE TITLE
Wrong url in ProjectIssueBoards

### ISSUE THREAD

**Issue by arthot** [jdalrymple/node-gitlab#113]
Hi, I think there is a mistake in `ProjectIssueBoards` service:

this code
``` javascript
const { ProjectIssueBoards } = require('gitlab');
new ProjectIssueBoards({ token }).all(projectId).then(r => console.log(r))
```
produces 404 error.

I've figured out that `ProjectIssueBoards` service has wrong url: 
https://gitlab.com/api/v4/products
instead of
https://gitlab.com/api/v4/projects

I presume it's just a typo, because I haven't found any evidence of existing **/products** url in the past

**Comment by jdalrymple** [comment]
Releasing this today!
