### ISSUE TITLE
ProjectMilestones#create completely ignores its title parameter

### ISSUE THREAD

**Issue by Ajedi32** [jdalrymple/node-gitlab#116]
See https://github.com/jdalrymple/node-gitlab/blob/0d14dff49b419b17d024fbe5ecb8a43b739b5335/src/templates/ResourceMilestones.js#L17-L21

The title parameter is unused. This results in errors where the GitLab API is complaining about the lack of a title parameter even though you did pass a title to the library.

**Comment by jdalrymple** [comment]
Will fix in a minute!

**Comment by Ajedi32** [comment]
Thanks.

As a side note, I'm a little surprised this particular issue wasn't caught by ESLint's no-unused-vars rule. Might want to check your config to see if that option is turned off...

**Comment by jdalrymple** [comment]
Yup i was just thinking that

**Comment by jdalrymple** [comment]
https://github.com/airbnb/javascript/issues/726 Apparently its like that on purpose. I must of overlooked it though.
