### ISSUE TITLE
jobs "most recent artifact" endpoint

### ISSUE THREAD

**Issue by arsdehnel** [jdalrymple/node-gitlab#121]
Right now we've got https://github.com/jdalrymple/node-gitlab/blob/master/src/services/Jobs.js#L16 as the endpoint to get artifacts from a specific job.  But there is also an endpoint for retrieving the most recent artifact without having to first get the job ID:

`https://example.com/<namespace>/<project>/-/jobs/artifacts/<ref>/raw/<path_to_file>?job=<job_name>`

More details on that endpoint here: https://docs.gitlab.com/ee/user/project/pipelines/job_artifacts.html#downloading-the-latest-artifacts

So my question is do people think it makes sense to add another method to the jobs service or should we make the `jobId` optional and if it's not specified we could use the most recent endpoint instead.

**Comment by jdalrymple** [comment]
I'm ok with that change ( the optional jobid) but it would be a breaking change since the jobid is the second argument :/

**Comment by jdalrymple** [comment]
Will be in next release
