### ISSUE TITLE
help for use of showArchive

### ISSUE THREAD

**Issue by madd35** [jdalrymple/node-gitlab#133]
Hi
I want to download project archive from gitlab with your library.
How can i use showArchive  from Repositories ?  any code example  pls ?

**Comment by jdalrymple** [comment]
Hey!

```
import { Repositories } from 'gitlab'

const repoAPI = Repositories({ token: 12345 });

const archive = await repoAPI.showArchive(yourProjectId)

// OR for a specifc branch
const archive = await repoAPI.showArchive(yourProjectId, {sha: master })

```

See here for more infomation about options https://docs.gitlab.com/ee/api/repositories.html#get-file-archive. Currently dont support format, but will add that soon.

Hope this helps!

**Comment by jdalrymple** [comment]
Did this help? @madd35
