### ISSUE TITLE
Tag Release API

### ISSUE THREAD

**Issue by Spareo** [jdalrymple/node-gitlab#135]
The gitlab API has the ability to add/edit release notes on tags. I have been looking over the source and can't find this feature in node-gitlab. Am I missing something or has it not be added to node-gitlab?

**Comment by jdalrymple** [comment]
Hasn't been added yet !

**Comment by Spareo** [comment]
Thanks for the quick reply, thats all I needed to know!

**Comment by jdalrymple** [comment]
Will get around to it though in the next week if you don't get to it :)

**Comment by Spareo** [comment]
Im kind of short on time this weekend and have already written code to just do it through the API. If you guys add it in the future I'll update my stuff to call it through this library.
