### ISSUE TITLE
TypeScript support

### ISSUE THREAD

**Issue by yonkeltron** [jdalrymple/node-gitlab#137]
Hello,

I would love to use this library in a TypeScript project but it seems that [the only type definitions](https://www.npmjs.com/package/@types/gitlab) are third-party and woefully outdated. Any chance of getting official TypeScript support in the project?

Thanks,
+Jonathan

**Comment by jdalrymple** [comment]
See #89, I'd like to finish moving things to ts, just running short on time lately :(.

**Comment by yonkeltron** [comment]
I understand how it is to run short on time and I want to take this chance to thank you for your efforts thus far. Is there some pre-release branch which we can help test?

**Comment by jdalrymple** [comment]
Its a huge team effort. Its wicked to see how everyone is pushing to make this library better. Yup! That is the current 'next' branch

**Comment by jdalrymple** [comment]
I just rebased, there may be a few hiccups

**Comment by damakawa** [comment]
Hello,

I'm trying to use the **next** branch, and I think I've found a few of the hiccups you mentioned.

Npm seems to be importing the module with no problems using the format `"gitlab": "git+https://github.com/jdalrymple/node-gitlab.git#next"` in the package.json dependencies.

However, when trying to import the module into a project file, the IDE isn't finding it in autocomplete, and adding it manually as `import * as GitLabApi from "gitlab";` is throwing the IDE error: 
```
[ts]
Could not find a declaration file for module 'gitlab'. '/Users/c74509/dev/TEA/gitrdonebot/node_modules/gitlab/dist/latest/index.js' implicitly has an 'any' type.
Try `npm install @types/gitlab` if it exists or add a new declaration (.d.ts) file containing `declare module 'gitlab';`
```

I went into the gitlabapi folder in node_modules and ran `npm run build`. The TS compiler is outputting the following errors:
```
src/infrastructure/XMLHttpRequester.ts:13:13 - error TS2348: Value of type 'typeof RequestHelper' is not callable. Did you mean to include 'new'?

13       await wait(sleepTime * 1000);
               ~~~~~~~~~~~~~~~~~~~~~~


src/services/MergeRequests.ts:101:26 - error TS2525: Initializer provides no value for this binding element and the binding element has no default value.

101   pipelines(projectId, { mergerequestId } = {}) {
                             ~~~~~~~~~~~~~~


src/services/Projects.ts:107:44 - error TS2304: Cannot find name 'Path'.

107   upload(projectId, filePath, { fileName = Path.basename(filePath) } = {}) {
                                               ~~~~


src/services/Projects.ts:115:18 - error TS2304: Cannot find name 'content'.

115           value: content,
                     ~~~~~~~
```

Here are my environment specs:
node version: 10.6.0
npm version: 6.1.0
tsc version: 2.9.2
IDE: VS Code 1.25.1

Is there any other information that I can provide? Thank you.

**Comment by jdalrymple** [comment]
Looks like the latest changes to the master branch havent be cleaned up for TS

**Comment by NearAutomata** [comment]
I started using this library for my bot which automates certain tasks and since I am using only TypeScript I have created generic "bandaid typings" to get some functions and auto completion at least: https://gist.github.com/NearAutomata/467cc36a92b1e89177ac956d4b04ddbf

As you can see, everything is typed with `...args: any[]` and `Promise<void>` thus far however I started to rewrite those functions I use internally with options interfaces and parameters such as

```typescript
interface IIssuesAllOptions {
    state?: "opened" | "closed";
    labels?: "No+Label" | string;
    // ...
}

export class Issues {
    // ...
    all(options?: { projectId: number, options?: IIssuesAllOptions }): Promise<any>;
    // ...
}
```

Furthermore I parsed the returned JSON objects to **partial** TypeScript interfaces such as

```typescript
export interface IIssue {
    id: number;
    iid: number;
    project_id: number;
    title: string;
    description: string;
    state: string;
    created_at: string;
    updated_at: string;
    closed_at: string;
    closed_by: IClosedByOrAuthor;
    labels?: (string)[] | null;
    milestone?: null;
    assignees?: (null)[] | null;
    author: IClosedByOrAuthor;
    assignee?: null;
    user_notes_count: number;
    upvotes: number;
    downvotes: number;
    due_date?: null;
    confidential: boolean;
    discussion_locked?: null;
    web_url: string;
    time_stats: ITimeStats;
    weight?: null;
}

export interface IClosedByOrAuthor {
    id: number;
    name: string;
    username: string;
    state: string;
    avatar_url: string;
    web_url: string;
}

export interface ITimeStats {
    time_estimate: number;
    total_time_spent: number;
    human_time_estimate?: null;
    human_total_time_spent?: null;
}
```

Until we get official typings I can suggest to try out my "bandaid typings" to get at least some auto completion :)

**Comment by lanaebk** [comment]
Thanks for the suggestion! I'll check it out.

**Comment by jdalrymple** [comment]
Rebased again, might be some more hiccups.

**Comment by casz** [comment]
@r00ger I will give it a spin in our botkit solution 😅

**Comment by r00ger** [comment]
Just to mention, a compiler does not emit type definitions along with js files. At the moment the code is loosely typed, so we don't want to emit loose type definitions. 

I'll start working on types once we have typescript in `master`

**Comment by casz** [comment]
@r00ger the package.json index needs to be fixed 😢 Could not find module basically.

**Comment by r00ger** [comment]
@casz can you elaborate?

**Comment by casz** [comment]
oh I missed the instruction to run build 😅

**Comment by casz** [comment]
The typescript dist seems to be running fine under nodejs 8 in a botkit environment 👍

**Comment by r00ger** [comment]
@jdalrymple what is the satisfactory level of testing that allows merging?

**Comment by jdalrymple** [comment]
All of you have been testing with it more than me, what still needs to be done? :)

**Comment by r00ger** [comment]
Merge 😀

**Comment by jdalrymple** [comment]
lol, ill create a beta build today and release it

**Comment by jdalrymple** [comment]
Done, released as 4.0.0 beta :)

**Comment by jdalrymple** [comment]
Hopefully no one has issues with that. If nothing major comes up in the next few days, ill merge it into master

**Comment by casz** [comment]
I'll give it a spin again :blush:

**Comment by jdalrymple** [comment]
Doesnt seem like anyones had any serious issues. Any objects to merging this in within the next few days?

**Comment by jdalrymple** [comment]
Updated the branch with the latest additions and published under 4.0.0-rc.1

**Comment by CWSpear** [comment]
@jdalrymple it appears as though when you published `4.0.0-rc.1`, you didn't publish the types.

**Comment by jdalrymple** [comment]
Oops!! Il fix that asap

**Comment by jdalrymple** [comment]
I publish the whole dist folder, but for some reason the types file gets transpiled oddly

```
import {} from '../src/index';

declare global {
    type temporaryAny = any;
    type UserIdOptions = { userId?: string };
}

```

```
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
```

**Comment by r00ger** [comment]
As I said, [above](https://github.com/jdalrymple/node-gitlab/issues/137#issuecomment-413795348)

> Just to mention, a compiler does not emit type definitions along with js files. At the moment the code is loosely typed, so we don't want to emit loose type definitions.
> I'll start working on types once we have typescript in master

**Comment by r00ger** [comment]
Hi there!

@jdalrymple did you get more feedback about rc release? What do you think of merge at this point?

**Comment by jdalrymple** [comment]
Nothing negative yet! Merge should be good now.

**Comment by r00ger** [comment]
@jdalrymple sooooo 🤔

**Comment by jdalrymple** [comment]
lol I still need to resolve the conflicts in the PR

**Comment by casz** [comment]
Now let the type definitions race begin 💪

**Comment by jdalrymple** [comment]
Released to npm!

**Comment by NearAutomata** [comment]
Regarding the types I will mention something rather obvious that I'd appreciate nonetheless. It'd be nice if you prioritise the typings of more common classes/APIs such as Project, User, MergeRequest and Issue first.

The initial typings before my adjustments I linked in my [previous comment](https://github.com/jdalrymple/node-gitlab/issues/137#issuecomment-411771028) we're created with the [dts-gen](https://github.com/Microsoft/dts-gen).

**Comment by jdalrymple** [comment]
Should this issue remain open for future types discussion? Or would it make more sense to have follow up issues for those things?

**Comment by jdalrymple** [comment]
Closing for now!

**Comment by jdalrymple** [comment]
Just note, these definitions have **only** be added to the next release
