### ISSUE TITLE
Cannot find module '@babel/runtime/core-js/object/define-property'

### ISSUE THREAD

**Issue by lipsumar** [jdalrymple/node-gitlab#140]
Just updated to `3.7.0` and as soon as i import `gitlab/dist/es5`, I get:

```
Error: Cannot find module '@babel/runtime/core-js/object/define-property'
    at Function.Module._resolveFilename (module.js:527:15)
    at Function.Module._load (module.js:476:23)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/John/my-project/on-demand-bulk-killer/node_modules/gitlab/dist/es5/index.js:7:30)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/John/my-project/on-demand-bulk-killer/lib/index.js:2:16)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
```

I'm using node `v8.7.0`

**Comment by jag-tus** [comment]
I had the same issue. I will end up upgrading to node v8 and using the ES6 version, but here is a hint to help you along the way.

I noticed the following lines in `dist/es5/index.js`:
```
var _Object$defineProperty = require("@babel/runtime/core-js/object/define-property");

var _Object$keys = require("@babel/runtime/core-js/object/keys");
```

If you look for these files in `node_modules/@babel/runtime/`, you will find that `core-js/` doesn't exist.  There are two fixes I can imagine:

1) Figure out the appropriate version of `babel-runtime` (the one that has `core-js`).
2) Update the `es5` version of this package. 
e.g. `var _Object$defineProperty = require("@babel/runtime/helpers/defineProperty");`. Note that I don't know what `keys` has been renamed to and how many other places you'll need to make this update.

Make sure that whatever changes you make, you make a pull-request and you meet all PR requirements (passing tests, etc).

Good luck!

**Comment by jag-tus** [comment]
If it's just a question of not being able to use the `import` keyword:

`const Gitlab = require('gitlab').default;`

**Comment by GreenGremlin** [comment]
Alternatively, with the import keyword:

``` javascript
const {default: Gitlab} = require('gitlab');
```

**Comment by BBKolton** [comment]
Does anyone know _why_ this update broke ES5 support? It was pretty frustrating having it work one day and break the next

**Comment by GreenGremlin** [comment]
My guess would be something changed in `@babel/runtime`, likely [this change](https://github.com/babel/babel/commit/a8224d40e2ff5d2ef92152e4853257596d8097bc#diff-7f5561cc60854021d1a8bd8d7303400d).

**Comment by GreenGremlin** [comment]
It looks like re-building and re-publishing might fix it.

**Comment by lipsumar** [comment]
Indeed, if I clone the project and rebuild it then it works. This is pretty annoying. @jdalrymple please rebuild and push updated version 🙏 

In the meantime here's what i have:

create a `install-gitlab.sh` file:
```bash
if [ -d "./node-gitlab" ]; then
  rm -rf ./node-gitlab
fi
git clone git@github.com:jdalrymple/node-gitlab.git
cd node-gitlab
npm install
npm run build
```

make it executable:
```
chmod u+x ./install-gitlab.sh
```

Add this to your package.json:
```
"preinstall": "./install-gitlab.sh"
```

Then change your dependency to your local copy:
```
  "dependencies": {
    "gitlab": "./node-gitlab"
  }
```

And finally `npm install`

**Comment by GreenGremlin** [comment]
Or just

```
npm install --save jdalrymple/node-gitlab
```

**Comment by jdalrymple** [comment]
Will do ASAP!! Sorry for all the trouble everyone :(

**Comment by jdalrymple** [comment]
I broke something. Still looking into it. For what ever reason, the release stage is failing due to a missing module that doesnt seem to be missing on the test or lint stages. https://travis-ci.org/jdalrymple/node-gitlab/jobs/413361700

**Comment by NBardelot** [comment]
This issue is blocking, and seems a little harder to fix than expected. Even rolling back to older versions of the 'gitlab' module does not work, because the @babel/runtime dependency is set to use the latest release in your package.json.

Would you please consider forcing the version of @babel/runtime to "7.0.0-beta.55" instead of "^7.0.0-beta.56" on the master? That would give you time to fix the issue on a branch, while unblocking every user hit by the issue like me. Thanks.

**Comment by jdalrymple** [comment]
Yup that seems like a smarter idea. I'll make the change today

**Comment by jdalrymple** [comment]
Hmm, i reverted it, but travis is still failing. I tried rerunning an old pipeline but it also failed with the same set of errors. I've also reset every babel related package back down to `7.0.0-beta.55` but there wasnt an improvement. Could this be related to npm/ travis in anyway? Sorry for all the hassle!!

**Comment by jdalrymple** [comment]
Hmm, not really sure why this isnt working. I set all the babel related packages to `7.0.0-beta.55` instead of `^7.0.0-beta.56 `  but travis is still failing with a module not found error. 

```
npm WARN prepare removing existing node_modules/ before installation
npm ERR! code MODULE_NOT_FOUND
npm ERR! Cannot find module '../pack.js'
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2018-08-08T15_00_40_854Z-debug.log
The command "eval npm ci  " failed. Retrying, 2 of 3.
/home/travis/.travis/job_stages: line 257: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed. Retrying, 3 of 3.
/home/travis/.travis/job_stages: line 257: ./node_modules/.bin/npm: No such file or directory
The command "eval npm ci  " failed 3 times.
The command "npm ci " failed and exited with 127 during .
```

Any other suggestions? Sorry for the all the hassle!

**Comment by jdalrymple** [comment]
May be related to this version of npm/node. Testing with v10.0.0

**Comment by jdalrymple** [comment]
I've also rerun the same job multiple times and have gotten different errors inconsistently ...

**Comment by jdalrymple** [comment]
Asking the travis team: https://github.com/travis-ci/travis-ci/issues/9965

**Comment by notsentient** [comment]
If you're using yarn you can add a `resolutions` key to your package.json

```json
  "resolutions": {
    "@babel/runtime": "7.0.0-beta.55"
  }
```

**Comment by jdalrymple** [comment]
Still no suggestions from the travis team. I guess il start stripping the build process to narrow down where the problem may be.

**Comment by Sechgulo** [comment]
Can confirm that forcing the @babel/runtime version to 7.0.0-beta.55 in our own package.json solved it (we're not using Travis in any way).

**Comment by jdalrymple** [comment]
It ended up being caused by the cached npm folder

**Comment by jdalrymple** [comment]
Does the var @babel/runtime/core-js/object/define-property error persist with the rc1 release of babel?

**Comment by jdalrymple** [comment]
Reopen if its still an issue!! :D
