### ISSUE TITLE
List all resource members, including inherited members

### ISSUE THREAD

**Issue by MrSnoozles** [jdalrymple/node-gitlab#141]
Hello,

as far as I can see ProjectMembers.all() only returns the members added to a project but not all members. The API endpoint for this is /projects/:id/members/all instead of /projects/:id/members. The endpoint is documented here https://docs.gitlab.com/ee/api/members.html#list-all-members-of-a-group-or-project-including-inherited-members

As far as I could see there is no way to retrieve all members yet. Did I maybe miss anything?

**Comment by jdalrymple** [comment]
Oops! I'll fix this tonight!

**Comment by MrSnoozles** [comment]
Awesome, thanks for the super quick reply

**Comment by jdalrymple** [comment]
```javascript
const membersIncludingInherited = await ProjectsMembers.all(id)
const membersWithoutInherited = await ProjectMembers.all(id, {excludeInherited: true})
```

Does this work for you :) ?

**Comment by MrSnoozles** [comment]
I'm pretty sure your changes are correct, but it doesn't work for my Gitlab 11.1.2. instance. It seems like this API endpoint is coming in 11.2: https://gitlab.com/gitlab-org/gitlab-ce/commit/046796cc3a98068e99abed152145e76c4636959c

Thank you so much for the quick response. I'm going to report back if it works once the endpoint becomes available :)

**Comment by max-wittig** [comment]
@jdalrymple I guess we can add this feature again, but I would vote to fall back to the old behavior in-case where the endpoint doesn't exist.

**Comment by jdalrymple** [comment]
Hmm, its supported in the latest Gitlab version right? For older behaviour wouldnt using an older version of the package make more sense. Ill finish up merging the typescript changes and then add this change as a breaking change. At least that way it will be obvious in the changelog

**Comment by max-wittig** [comment]
@jdalrymple Maybe a hint in the README would also be useful, that it only supports 11.2 and up.

**Comment by MrSnoozles** [comment]
I would probably keep things backwards compatible and give an option to
`IncludeInherited` instead of excluding them. That way it would still work
for old versions of the API. Kind of makes sense too, because it's closer
to Gitlabs behaviour (/members Vs explicitly calling /members/all)

Max Wittig <notifications@github.com> schrieb am Di., 4. Sep. 2018, 07:09:

**Comment by jdalrymple** [comment]
@casz Its definitely semantic if i release a major version, though its a little extreme for this addition lol. Sounds good though, ill change it to be inclusive as opposed to exclusive!

**Comment by casz** [comment]
Well when I updated you broke my project overview, and I had to either revert or fall in line and the release you did earlier did not show it as breaking.

This commit should have been marked breaking in my honest opinion, since it broke my project overview (that depended no inheritance), cause it broke the previous default behavior and also did not exist in the current API (but that was more of a GitLab issue 😅)
https://github.com/jdalrymple/node-gitlab/commit/e081a1629f33e3af172101b94977f281879539c9

**Comment by jdalrymple** [comment]
Yea i messed it up when i first did it! I would do it properly for the next time.
