### ISSUE TITLE
TypeError: Cannot read property 'headers' of undefined at getPaginated

### ISSUE THREAD

**Issue by rohan-deshpande** [jdalrymple/node-gitlab#142]
Error is occurring at `RequestHelper.js:116:44` when attempting the following

```javascript 
const gitlab = new GitLab({ url, token });

describe('projects', () => {
  it('should fetch projects as an array', done => {
    gitlab
      .Projects
      .all()
      .then(projects => {
        console.log(projects);
        done();
      })
      .catch(console.log);
  });
});
```

Note that I can access the projects via postman with

```
{{gitlab}}/api/v4/projects?private_token={{token}}
```

**Comment by jdalrymple** [comment]
hmm, ill look!

**Comment by jdalrymple** [comment]
What version of the package are you using? And do you have problems running any of the other functions?

**Comment by rohan-deshpande** [comment]
Ah sorry, `3.7.0`, nothing really seems to work

**Comment by jdalrymple** [comment]
Hmm thats really odd... Looking!

**Comment by jdalrymple** [comment]
Could you check if you get the same problem in an earlier version of the package?

**Comment by rohan-deshpande** [comment]
Can do, let's just make sure this is not a user error first though, are you expecting the `url` prop passed to the constructor to contain the `/api/v4` suffix or are you appending it? I wasn't really clear about this.

**Comment by jdalrymple** [comment]
I append it internally, the url just need to be the base url, like: https://gitlab.com

**Comment by rohan-deshpande** [comment]
Heh, okay, it's a certificate issue. I'm behind a proxy.

**Comment by rohan-deshpande** [comment]
Hmm wonder how I can get around it...

**Comment by jdalrymple** [comment]
hmm, could it be an issue with the Request module? Can you access the API directly through the Request module ?

**Comment by rohan-deshpande** [comment]
Do you mean the `RequestHelper` class?

**Comment by jdalrymple** [comment]
Nope, i mean with the Request Library: https://www.npmjs.com/package/request

**Comment by rohan-deshpande** [comment]
Ah right so you're using this to perform the requests, let me try.

**Comment by jdalrymple** [comment]
yup! It will help narrow down where the error is coming from

**Comment by rohan-deshpande** [comment]
Okay yeah, happens there too. I can get around it by passing an option to the call like 

```
const rejectUnauthorized = false;

request({ url, rejectUnauthorized });
```

Are all options passed to the constructor passed down to the request call? If so then passing this as an option should just work.

**Comment by jdalrymple** [comment]
No the options are not passed down :( If there another way around that problem?

**Comment by rohan-deshpande** [comment]
I don't think so. It's a legit use case imo because in some corporate environments, non standard certs are used or certificates are not managed by the developers themselves making it hard to have any kind of control over them.

**Comment by jdalrymple** [comment]
Hmm, i agree. How does this flag work with other request modules? For example we use the XMLHttpRequest module as well in this library ? (Eventually to be refactored out to support any request module the user would like #98

**Comment by rohan-deshpande** [comment]
Any reason why you are using two libraries? Why not just use `node-fetch`?

**Comment by jdalrymple** [comment]
I started with the Request module because it was one of the most used/well tested request modules i could find. The XML request module was added after to support xhr request for the browser. A better library to upgrade to may be cross-fetch, which handles all of these cases. Before switching the main request library around, id like to do more research to at least try and maintain the same API if possible instead of having to update everything

**Comment by rohan-deshpande** [comment]
Ah okay makes sense. I think `node-fetch` might be the best option then because the implementation is identical to the browser spec.

**Comment by jdalrymple** [comment]
Meh, this library was build specifically for node, so whether it maintains adherence to the browser spec is less important. As long as it is consistent s'all good. Another one another contributor suggested was axios?

**Comment by rohan-deshpande** [comment]
I wouldn't use Axios personally. Fetch is the way forward.

**Comment by MartinBenninger** [comment]
I think this is actually an issue with the node-gitlab library and not just the request package.

We use this library in the browser with the XMLHttpRequester and we get the same error whenever a request fails.

`TypeError: Cannot read property 'headers' of undefined`

This happens for example when making a request to a repository that the user does not have access to. Previously the real HTTP error was passed to the error function.

I think that it's coming from the bit of code that tries to get the sleep time from the 'retry-after' header. 

`const sleepTime = parseInt(err.response.headers['retry-after'], 10);`

Let me know if you need any more information. I can also try to make a small sample to reproduce the error.

**Comment by jdalrymple** [comment]
Hmm, alright I'll look into it tonight

**Comment by jdalrymple** [comment]
There are two problems in this issue lol 1. Certificates but @casz has pointed out how to handle that, and 2. The sleep propagating `header not found` errors. This second one im working on now!

**Comment by jdalrymple** [comment]
Pushed up a fix for the headers

**Comment by casz** [comment]
@rohan-deshpande you really ought to handle certs in the way that I suggested above. This other way is just an excuse.
All you have to do is take your company root CA and put it into the pem file.

If you want to include more you simply add them all into one pem file, there is really no excuse to not doing it.

**Comment by rohan-deshpande** [comment]
Of course I’ve already tried this. The certs are not actually valid. That’s the problem. I don’t think it’s helpful to assume that everything is as it should be in the myriad of corporate mess that others have to deal with.

**Comment by jdalrymple** [comment]
Although i agree with @casz , I see your point. If the user of the library is ok with ignoring certs that's their business.

**Comment by rohan-deshpande** [comment]
I agree 100% in principle as well. It’s just that these things aren’t always as they should be.

**Comment by rohan-deshpande** [comment]
Nice one, thanks.
