### ISSUE TITLE
Add CLI functionality

### ISSUE THREAD

**Issue by mdsb100** [jdalrymple/node-gitlab#146]
Hi, I am maintaining [cli-gitlab](https://github.com/mdsb100/cli-gitlab). I want to refactor to upgrade node-gitlab@v3.7.0.

I have an idea to use the decorators to provide CLI, then I don't have to maintain a CLI map. So I plan to fork this project and directly plus a decorators into the service.

If you can accept my pull request, which is to provide CLI in this project, then I don't need to publish a npm library of cli-gitlab@2.0.0.

Can you accept my idea？

**Comment by jdalrymple** [comment]
That would be interesting! Adding CLI capabilities would be pretty cool. Could you provide an example of how you could do this with decorators?

**Comment by mdsb100** [comment]
I am coding.
See also https://github.com/mdsb100/node-gitlab, branch is 'cli'

**Comment by jdalrymple** [comment]
Cool!! Would this need to be changed if the library moved to typescript?

**Comment by mdsb100** [comment]
Typescript can use decorators too.The CLI code still be es6 or ts as your want.
If there has a map, The CLI made with map easiler than decoaratora.

About map, I have a idea. Write a script to requeat official document and auto create map.If we do not do this, I think use decorators describe api is a good way.

example: 
```
@api('userID', {action: post, namespace:xxx})
```

**Comment by jdalrymple** [comment]
Here was the discussion about creating the map #104

**Comment by mdsb100** [comment]
#147

**Comment by mdsb100** [comment]
what is going on?

**Comment by jdalrymple** [comment]
I reopened this as to not forget about adding these changes :)
