### ISSUE TITLE
node-gitlab creates peer dependency warning

### ISSUE THREAD

**Issue by casz** [jdalrymple/node-gitlab#154]
Depending on node-gitlab creates peer dependency warning

```
npm WARN @semantic-release/npm@5.0.1 requires a peer of semantic-release@>=15.9.0 <16.0.0 but none is installed. You must install peer dependencies yourself.
```

**Comment by jdalrymple** [comment]
Hmm, not sure why this warning would occur though since     "semantic-release": "^15.9.3" is installed and that is within the range thats required.
