### ISSUE TITLE
Rate limiting doesn't work anymore

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab#165]
Looks like node-gitlab no longer obeys the rate-limit, but throws 429 again.

I'm guessing that it broke in https://github.com/jdalrymple/node-gitlab/commit/bc3b366ac69abdab10ed3c002dd07632a7b9a044#diff-6e04893ff7542559430b953f9c1293d0

**Comment by casz** [comment]
Yes I wondered the same when I saw the commit. Your welcome to open a PR to fix it and then you can also verify it is working

Perhaps a mock test to avoid breaking it again :smile:

**Comment by max-wittig** [comment]
I think it still works, but I've only implemented it for get requests for some reason before in https://github.com/jdalrymple/node-gitlab/commit/9b4625061976505c46bd4cf2cd207cc7c7ab4eb3

**Comment by jdalrymple** [comment]
Not sure how i didnt notice that before smh. Depending on #98 the got library handles retries too!

**Comment by max-wittig** [comment]
@jdalrymple Rate limiting actually broke again with the new custom requester approach. I still don't know how to use the custom requesters. There seem to be no example on how to use `got` for example. I'm just importing the library like so and no requester is defined: 

```js
const {Gitlab} = require('@gitbeaker/node');
```

**Comment by jdalrymple** [comment]
Sorry this is on me! Latest build has some issues apparently #885. Looking into this now!
