### ISSUE TITLE
Add support to login using username / password to generate access tokens

### ISSUE THREAD

**Issue by jmls** [jdalrymple/node-gitlab#180]
I was wanting to use this library as a middleware for linking my app with gitlab. 

Looking at the code, there seems to be no "connection" made, just setting up the token etc

What I am slightly confused about is that there seems to be no api to "login" as such - it assumes that the token is known.

How can I supply my users with a login "form" (username / password) and log into gitlab initially, in order to obtain the private token ?

**Comment by jdalrymple** [comment]
Hmm, i think the gitlab api did have a session API at one point, but they deprecated it. So, im not really sure off the top of my head. You could make calls to the website which would provide you wish a session token and use that token in the API i *think*, though ive never tried,

**Comment by jmls** [comment]
I have found this 

https://docs.gitlab.com/ce/api/oauth2.html#resource-owner-password-credentials

> POST request to /oauth/token with parameters:
> 
> {
>   "grant_type"    : "password",
>   "username"      : "user@example.com",
>   "password"      : "secret"
> }

I have tried using curl, and that does return an `access_token` 

Is there a call in node-gitlab that calls this api ? 

thanks

**Comment by casz** [comment]
Actually you can see how it can be done here:
They allow username password but then create a API token for it self.
https://github.com/rgl/gitlab-source-link-proxy

**Comment by jdalrymple** [comment]
@jmls Not yet! but we can add that ability soon. @casz Thanks for the reference!

**Comment by marco-silva0000** [comment]
would it be viable to use ssh keys for authentication? I don't think this library supports that, but I would like to use the team members already generated ssh keys to automate some behaviour that uses gitlab authentication
https://github.com/bufferoverflow/verdaccio-gitlab/issues/51

**Comment by casz** [comment]
ssh keys cannot be used from API nor website as authentication. This is a limitation from Gitlab. That is likely to never change, ever.

**Comment by sdc224** [comment]
Guys any update over this issue? I mean how to use it, how to generate the access token from username and password?

**Comment by jdalrymple** [comment]
I don't foresee us adding this feature since Gitlab itself prefers users use a token
