### ISSUE TITLE
Request URL got modified unexpectedly when using the projects API

### ISSUE THREAD

**Issue by trexguo** [jdalrymple/node-gitlab#184]
Hi, I am using the latest version of the package with Koa on Node 8.11. I got this strange error when trying to call the _Projects_ API

```javascript
  getProjects: async (ctx, next) => {
    const { token } = ctx.query
    const api = new Gitlab({
      url: config.gitlab.url, // Defaults to http://gitlab.com
      token: token // Can be created in your profile.
    });

    const projectList = await api.Projects.all();

    ctx.state.code = 1;
    ctx.state.data = projectList;
  }
````

> Catch Error: { StatusCodeError: 404 - {"error":"404 Not Found"} at new StatusCodeError (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request-promise-core\lib\errors.js:32:15) at Request.plumbing.callback (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request-promise-core\lib\plumbing.js:104:33) at Request.RP$callback [as _callback] (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request-promise-core\lib\plumbing.js:46:31) at Request.self.callback (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\request.js:185:22) at emitTwo (events.js:126:13) at Request.emit (events.js:214:7) at Request.<anonymous> (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\request.js:1161:10) at emitOne (events.js:116:13) at Request.emit (events.js:211:7) at IncomingMessage.<anonymous> (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\request.js:1083:12) at Object.onceWrapper (events.js:313:30) at emitNone (events.js:111:20) at IncomingMessage.emit (events.js:208:7) at endReadableNT (_stream_readable.js:1064:12) at _combinedTickCallback (internal/process/next_tick.js:138:11) at process._tickCallback (internal/process/next_tick.js:180:9) From previous event: at Request.plumbing.init (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request-promise-core\lib\plumbing.js:36:28) at Request.RP$initInterceptor [as init] (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request-promise-core\configure\request2.js:41:27) at new Request (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\request.js:127:8) at request (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\index.js:53:10) at Function.get (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\request\index.js:61:12) at getPaginated (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\gitlab\dist\latest\infrastructure\RequestHelper.js:86:44) at getPaginated (D:\Dev\EL\Gitlab-WeApp-Helper\server\node_modules\gitlab\dist\latest\infrastructure\RequestHelper.js:95:18) at <anonymous> name: 'StatusCodeError', statusCode: 404, message: '404 - {"error":"404 Not Found"}', error: { error: '404 Not Found' }, options: { url: 'https://git.mydomain.com/api/v4/http://git.mydomain.com/api/v4/projects?archived=false&membership=false&order_by=created_at&owned=false&page=2&per_page=20&simple=false&sort=desc&starred=false&statistics=false&with_custom_attributes=false&with_issues_enabled=false&with_merge_requests_enabled=false', headers: { 'private-token': 'XXXXXXXXXX' }, 

As you can see the URL was duplicated for some reasons:
>  options: { url: 'https://git.mydomain.com/api/v4/http://git.mydomain.com/api/v4/projects?.........

Could you have a look at this? THX

**Comment by trexguo** [comment]
config.gitlab.url = "https://git.mydomain.com"
No. I have tested the _Users.current()_ and _Issues.all()_ endpoints as I need them in my app. There is no problem in them.

**Comment by casz** [comment]
I am using the Projects.all with no trouble.

**Comment by jdalrymple** [comment]
Thats really odd. Can you try printing this:

```
const api = new Gitlab({
      url: config.gitlab.url, // Defaults to http://gitlab.com
      token: token // Can be created in your profile.
    });

 console.log(api.Projects)
```

What are the properties of the Projects?

**Comment by trexguo** [comment]
```javascript
Projects {
  url: 'https://git.mydomain.com/api/v4',
  headers: { 'private-token': 'XXXXXXXXXX' },
  requester:
   { [Function: request]
     get: [Function],
     head: [Function],
     options: [Function],
     post: [Function],
     put: [Function],
     patch: [Function],
     del: [Function],
     delete: [Function],
     jar: [Function],
     cookie: [Function],
     defaults: [Function],
     forever: [Function],
     Request:
      { [Function: Request]
        super_: [Object],
        debug: undefined,
        defaultProxyHeaderWhiteList: [Array],
        defaultProxyHeaderExclusiveList: [Array] },
     initParams: [Function: initParams],
     debug: [Getter/Setter],
     bindCLS: [Function: RP$bindCLS] },
  useXMLHttpRequest: false,
  rejectUnauthorized: true }
```

**Comment by trexguo** [comment]
![20180904212602](https://user-images.githubusercontent.com/5989880/45034141-315d3400-b089-11e8-8536-ced8a2612803.png)

**Comment by trexguo** [comment]
![image](https://user-images.githubusercontent.com/5989880/45034230-741f0c00-b089-11e8-8195-8e2e62e4ac8c.png)

**Comment by jdalrymple** [comment]
I see it!

**Comment by jdalrymple** [comment]
So when it does the pagination, it attempts to fix this problem by replacing the duplication with an empty string since the url and the domain are passed in as two different arguments. The problem here is that the pagination url is coming back as http and not https which results in the regex not matching the strings.

change config.gitlab.url to be `http://git.mydomain.com` and it should work!
