### ISSUE TITLE
Update the user profile API

### ISSUE THREAD

**Issue by valentineus** [jdalrymple/node-gitlab#186]
Greetings and thank you for the excellent library!

I'm confused. I need to update the profile fields and I do not understand how I can do this.

The [documentation says](https://github.com/gitlabhq/gitlabhq/blob/master/doc/api/users.md#user-modification) that there is such an opportunity.
I have experienced [all the visible methods](https://github.com/jdalrymple/node-gitlab/blob/master/src/services/Users.ts#L5-L70) and can not get what I want.

Do I make a mistake somewhere?

**Comment by jdalrymple** [comment]
It looks like we are missing the edit function!! It will be added soon!
