### ISSUE TITLE
Get the current authenticated user

### ISSUE THREAD

**Issue by sambunting** [jdalrymple/node-gitlab#199]
Hi,

I'm having trouble trying to get myself when using the `Users` endpoint. 

If I was to use `git.Users()`, I would get an error saying `git.Users is not a function`, and adding an empty object to all making it `git.Users.all({})` results in it still printing out everyone instead of just me.

Is there something I'm missing here? I can't seem to figure out how I can get information like the authenticated users username using the package.

**Comment by jdalrymple** [comment]
Closing this for now! If there are any more problem feel free to comment!
