### ISSUE TITLE
Need example of create/update a file/branch/repo with v4 API (V3 working for me)

### ISSUE THREAD

**Issue by anirbanctts** [jdalrymple/node-gitlab#202]
Hi,
Can someone please share example of get/create/update a file/branch/repo with v4 API (V3 working for me) using "gitlab" package?
V3 usage
---------
```
var gitlab = require('gitlab');
var client = gitlab({url:url,oauth_token:accessToken});
client.Projects.repository.listTree(repoFullName,{path,ref});
client.projects.repository.showFile({projectId, file_path,ref:modelInfo.branch});
client.projects.repository.createFile({projectId, file_path, branch_name, content: content, commit_message});
.....
```
Need assistance with v4 example

Basic reading repo and branches working fine
```
var gitlab = require('gitlab/dist/es5').default
var client = new gitlab({url:url,oauthToken:accessToken});
client.Projects.all();
or
client.Branches.all(projectid);   
```
But getting files list in a path, getting specific file method calls I am not able to figure out 

# Install from npm 
npm install gitlab
required version: latest (4.1.1)

**Comment by jdalrymple** [comment]
The main difference in v3 to v4 is the breakdown of the APIs has been changed to match Gitlabs docs

```javascript
//https://docs.gitlab.com/ee/api/repositories.html
client.Repositories.tree(..)

// https://docs.gitlab.com/ee/api/repository_files.html
client.RepositoryFiles.show(..)
client.RepositoryFiles.create(..)
```

**Comment by anirbanctts** [comment]
I think I got the hang of it. Thanks a ton
