### ISSUE TITLE
Gitlab API `Sudo` Support

### ISSUE THREAD

**Issue by defenestration** [jdalrymple/node-gitlab#203]
I was looking at checking if a user has access to a project, i found a sudo command documented in the api ( https://docs.gitlab.com/ee/api/#sudo ).  I'm unable to tell if this is implemented in this project though.  

I think I can create an impersonation token and create a new instance of the api with that, but sudo seems like it would be the better option since it wouldn't have to create/remove tokens.

**Comment by defenestration** [comment]
It looks like you can pass it as a header in the request, the example they give is:

`curl --header "Private-Token: 9koXpg98eAheJpvBs5tK" --header "Sudo: username" "https://gitlab.example.com/api/v4/projects"
`

**Comment by defenestration** [comment]
I was able to confirm this will work with a post request, the following opens the issue under the 'notme' user:

`curl --header "Content-Type: application/json" --header "Private-Token: XYZ" --header "Sudo: notme" "https://git.site.com/api/v4/projects/6/issues" -d '{ "title": "testissue" }'`

**Comment by jdalrymple** [comment]
We could add it as an option on initatiation such that its passed on the header:

```javascript
const gitlab = new Projects({
  token: dwedew
  sudo: true
})

**Comment by defenestration** [comment]
Yeah that would work out fine. Either that or a way to pass it dynamically on an existing object, but that would probably be more annoying to implement.

**Comment by jdalrymple** [comment]
Do you think dynamically passing it would be used more often ? Yea it would be a pain to implement, but if it's a more frequent use case, we can put in the time.

**Comment by defenestration** [comment]
I can't say that it would for sure, but I am probably not the best person
to ask . I think the method you suggested will be fine though.

**Comment by jdalrymple** [comment]
## Proposal:

Add sudo option to the constructor of a Service. If this option is present, add the sudo header such that all calls made with the service instance contain this header.
