### ISSUE TITLE
Creating png file from buffer | content is invalid

### ISSUE THREAD

**Issue by anirbanctts** [jdalrymple/node-gitlab#205]
Getting: StatusCodeError: 400 - {"error":"content is invalid"}
using
```
client.RepositoryFiles.create(projectid, path, branch, {content: content, encoding: 'base64', commit_message: message}).then(callback);
```
When buffer was printed in console - ```<Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 05 01 00 00 03 0f 08 06 00 00 00 65 a0 13 26 00 00 20 00 49 44 41 54 78 5e ec dd 09 dc 95 73 fe ... >```

Please suggest

buffer was created with....
At Client
---------
```   
            // converts blob to base64
                var blobToBase64 = function(blob, cb) {
                    var reader = new FileReader();
                    reader.onload = function() {
                    var dataUrl = reader.result;
                    var base64 = dataUrl.split(',')[1];
                    cb(base64);
                    };
                    reader.readAsDataURL(blob);
                };
                
                blobToBase64(blob, function(base64) { // encode

                    var updateBlob = {'blob': base64};
                    //calling save image blob API
```

At Server
------------
 ``` var gitlab = require('gitlab');
var client = gitlab({url:url,oauth_token:accessToken});
  var content = new Buffer(modelInfo.body.blob, 'base64'); // decode
```

_Originally posted by @anirbanctts in https://github.com/jdalrymple/node-gitlab/issues/200#issuecomment-424995065_

**Comment by anirbanctts** [comment]
Hi, Any update?

**Comment by anirbanctts** [comment]
Let me know when you can, still waiting for the resolution. Have only few days left for going live

**Comment by jdalrymple** [comment]
So ive tested this code with text content and it seems to work. It only fails when i test with base64 data. Im going to keep testing and see what i can come up with.

**Comment by jdalrymple** [comment]
Here got it to work, just needed to encode my image properly:

```javascript
	const Gitlab = require('../../node-gitlab').default;

	const { RepositoryFiles } = new Gitlab({
		token: 'token',
	});

	const content = await Fs.readFile('small.png');

	await RepositoryFiles.create(id, 'fake2.png', 'master', {
		content: content.toString('base64'),
		encoding: 'base64',
		commit_message: 'message',
	});
```

**Comment by casz** [comment]
Perhaps make it a unit test and provide the example in readme? 😇 🙌

**Comment by anirbanctts** [comment]
Thanks a lot. Closing the issue. will try to add to the documentation
