### ISSUE TITLE
@types/gitlab outdated

### ISSUE THREAD

**Issue by simonmeusel** [jdalrymple/node-gitlab#207]
## Description
The typings for node-gitlab https://www.npmjs.com/package/@types/gitlab are very very old

## Possible fixes
* Remove the typings
* Update the typings

**Comment by r00ger** [comment]
I'm in a process of adding types https://github.com/jdalrymple/node-gitlab/pull/185

**Comment by jdalrymple** [comment]
It isnt unfortunately :(. I dont see why we could make a PR though!

**Comment by simonmeusel** [comment]
https://github.com/DefinitelyTyped/DefinitelyTyped#removing-a-package

**Comment by simonmeusel** [comment]
I think we should create a PR when #185 is done

**Comment by jdalrymple** [comment]
#185 Has been merged! :D

**Comment by simonmeusel** [comment]
Ok, I'm going to create a PR at https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by simonmeusel** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/30249

**Comment by simonmeusel** [comment]
Typings are now removed

**Comment by casz** [comment]
@simonmeusel thanks 🙌
