### ISSUE TITLE
Do you have Gitlab create project API ？

### ISSUE THREAD

**Issue by frontlove** [jdalrymple/node-gitlab#218]
## Description
I want to create project in Gitlab. Do you have Gitlab create project API?

**Comment by casz** [comment]
If you bothered looks at the example or source code you had your answer:
https://github.com/jdalrymple/node-gitlab#examples
https://github.com/jdalrymple/node-gitlab/blob/master/src/services/Projects.ts#L17

**Comment by jdalrymple** [comment]
Yup! See the above links @casz Thanks!

**Comment by frontlove** [comment]
> 如果你想看看你得到答案的例子或源代码：[https](https://github.com/jdalrymple/node-gitlab#examples)：
> [//github.com/jdalrymple/node-gitlab#examples](https://github.com/jdalrymple/node-gitlab#examples)
> [节点gitlab / src目录/服务/ Projects.ts](https://github.com/jdalrymple/node-gitlab/blob/c56e0525aad89f19b43591813da0c2157bd8b64c/src/services/Projects.ts#L17)
> 
> [c56e052中的](/jdalrymple/node-gitlab/commit/c56e0525aad89f19b43591813da0c2157bd8b64c) 第17 [行](/jdalrymple/node-gitlab/commit/c56e0525aad89f19b43591813da0c2157bd8b64c)
> 
> create（options）{

Thank you very much!
