### ISSUE TITLE
Can't get commits list from project

### ISSUE THREAD

**Issue by FCHAPLIN** [jdalrymple/node-gitlab#233]
## Description
Can't get single project
Can't get commit lists from project.

## Steps to reproduce

The only way I could get a project object is this :
```
api.Projects.all({owned: true})
  .then((projects) => {
    let project = projects.filter(function (project) {
      return project.id === MYPROJECTID;
    })[0];
```
Is there a better way ?

Then I try to get the list of commits on develop: 
(https://github.com/jdalrymple/node-gitlab/issues/36 solution is not working for me...)
```
 api.Commits.all(project.id, {
      ref_name: 'develop'
    }).then((commits) => {
        console.log(commits);
      });
```
The official gitlab api documentation says : 
`GET /projects/:id/repository/commits`

If i do curl in terminal : 
`curl --header "PRIVATE-TOKEN: ---MYTOKEN----" https://gitlab.com/api/v4/projects/MYPROJECTID/repository/commits`
It works.

How do I write this with your api ?

## Expected behaviour
Return a list of commits

## Actual behaviour
UnhandledPromiseRejectionWarning: StatusCodeError: 404 - {"error":"404 Not Found"}

## Possible fixes

Writing real documentation would really help. This project would be really helpfull if we could use it.

**Comment by jdalrymple** [comment]
I'll fix the pagination problems ASAP!

**Comment by jdalrymple** [comment]
Related #225. Will be fixed in the next release!
