### ISSUE TITLE
Maintain logs for each API

### ISSUE THREAD

**Issue by sathik-basha** [jdalrymple/node-gitlab#236]
## Maintaining API logs.
 Automatically create day name structured file ex: (jan-23.txt) 
 File contents are
--->
6:33 https://gitlab.com/api/v4/projects/
7:15 https://gitlab.com/api/v4/projects/123/members

cc : @jdalrymple

**Comment by jdalrymple** [comment]
Can you please fill out the template above as best as you can. This will help in understanding what exactly you are proposing

**Comment by sathik-basha** [comment]
@jdalrymple  Sounds great

**Comment by jdalrymple** [comment]
Closing in favour of #279
