### ISSUE TITLE
showPagination documentation is innacurate

### ISSUE THREAD

**Issue by demetriusnunes** [jdalrymple/node-gitlab#238]
**Description**

`let { data, pagination } = await api.Projects.all({ perPage:40, maxPages:2, showPagination: true });`
 
The `showPagination` option only works if you specify the `page` parameter as well. Otherwise, is ignored.

**Comment by jdalrymple** [comment]
yup Ill update the docs. Pagination only works when you specify a page, otherwise it will not paginate and return **all** the results. Does that make sense? Maybe I should return pagination information if you specify maxPages since its less pages then the possible total about of pages

**Comment by jdalrymple** [comment]
So ill change it such that if you specify the maxPages or a singular page, then you can see the pagination information. Otherwise its not really helpful since youll be getting back all the results.

**Comment by jdalrymple** [comment]
Just pushed up this change!
