### ISSUE TITLE
Export the typescript definitions

### ISSUE THREAD

**Issue by tblaisot** [jdalrymple/node-gitlab#245]
**Description**
Actually there a npm package @types/gitlab saying:
"Stub TypeScript definitions entry dor gitlab, which provides its own types definitions"
But... the is not exported .d.ts in the  gitlab package on npm.
As the project itself is written in typescript it should not be hard to export definitions.

**Proposal**
Please generate and include the .d.ts files in the npm release and add "types" field in the package.json

**Comment by casz** [comment]
@tblaisot see https://github.com/jdalrymple/node-gitlab/pull/216

**Comment by tblaisot** [comment]
Thanks @casz , I hadn't search in PR for this change, I should have :)
Hope it will land soon !

**Comment by casz** [comment]
You can always use `npm install -S gitlab@next` to test it 😅

**Comment by tblaisot** [comment]
I just done that.
Work well for my need but i am a little desapointed that there is no typing
for api return objects...
Typing it via interfaces would be more user friendly :-)

Le jeu. 6 déc. 2018 à 17:44, Joseph Petersen <notifications@github.com> a
écrit :

**Comment by jdalrymple** [comment]
Working on it lol

**Comment by casz** [comment]
The intention is to add return types, your welcome to contribute 😅
