### ISSUE TITLE
add Group update capability

### ISSUE THREAD

**Issue by jennparise** [jdalrymple/node-gitlab#246]
**Description**
I am not seeing the ability to update a group only create
**Proposal**
  edit(groupId: GroupId, options: RequestOptions) {
    const gId = encodeURIComponent(groupId);
    return RequestHelper.put(this, `groups/${gId}`, options);
  }

**Comment by jdalrymple** [comment]
Must of missed that one lol will add ASAP, probably in the next branch

**Comment by jdalrymple** [comment]
Added to the next branch! Give the last couple commits a look to make sure i didnt miss anything :)

**Comment by jdalrymple** [comment]
Deployed in the next release on npm !
