### ISSUE TITLE
Groups LDAP group link

### ISSUE THREAD

**Issue by jennparise** [jdalrymple/node-gitlab#247]
---

**Description**
add ldap group link functionality
**Proposal**
in Groups: 
    ldap_group_link(groupId, options){
        const gId = encodeURIComponent(groupId);
        return infrastructure_1.RequestHelper.post(this, `groups/${gId}/ldap_group_links`, options);   
    }

  ldap_group_link(groupId: GroupId, options: RequestOptions) {
    const gId = encodeURIComponent(groupId);

    return RequestHelper.post(this, `groups/${gId}/ldap_group_links`, options);
  }

**Comment by jdalrymple** [comment]
Added to the next branch! Give the last couple commits a look to make sure i didnt miss anything :)

**Comment by jdalrymple** [comment]
Deployed in the next release on npm !
