### ISSUE TITLE
Pipeline.create not work with .variables

### ISSUE THREAD

**Issue by MrCheater** [jdalrymple/node-gitlab#254]
**Description**
version: "5.0.0-rc.7"

```
const PipelinesService = new Gitlab.Pipelines({
  token: 'XXX-XXX-XXX'
})

await PipelinesService.create(gitlabProjectId, 'ci/cd', {
  variables: {
    PULL_REQUEST_NAME: `${pullRequest.title}`,
    PULL_REQUEST_NUMBER: `${pullRequest.number}`,
    HEAD_COMMIT_SHA: `${pullRequest.head.sha}`,
    MERGE_COMMIT_SHA: `${pullRequest.merge_commit_sha}`,
    SOURCE_BRANCH_NAME: `${pullRequest.head.ref}`,
    SOURCE_BRANCH_SHA: `${pullRequest.head.sha}`,
    TARGET_BRANCH_NAME: `${pullRequest.base.ref}`,
    TARGET_BRANCH_SHA: `${pullRequest.base.sha}`
  }
})
```

Error:

```
{ HTTPError: Response code 500 (Internal Server Error)
    at EventEmitter.emitter.on (/home/mrcheater/resolve/node_modules/got/source/as-promise.js:74:19)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)


{"ref":"ci/cd","variables":{"p_u_l_l__r_e_q_u_e_s_t__n_a_m_e":"Feature/Transactional read models","p_u_l_l__r_e_q_u_e_s_t__n_u_m_b_e_r":"950","h_e_a_d__c_o_m_m_i_t__s_h_a":"d5c03dca7b2688f914eec50382b064d63ac9caad","m_e_r_g_e__c_o_m_m_i_t__s_h_a":"cacfdc22f0a5a2c50806f0d5ab99dfd259ff3878","s_o_u_r_c_e__b_r_a_n_c_h__n_a_m_e":"feature/transactional-read-models","s_o_u_r_c_e__b_r_a_n_c_h__s_h_a":"d5c03dca7b2688f914eec50382b064d63ac9caad","t_a_r_g_e_t__b_r_a_n_c_h__n_a_m_e":"dev","t_a_r_g_e_t__b_r_a_n_c_h__s_h_a":"8a09550de60c4c9fee24708f959f76ad6f144156"}}

```

**Possible fixes**
Maybe error in https://github.com/jdalrymple/node-gitlab/blob/next/src/infrastructure/RequestHelper.ts#L21

Maybe i have a bad "variables" format

**My workaround**
```
const request = require('request')

request(
  {
    method: 'post',
    body: {
      token: gitlab.token,
      ref: gitlab.ref,
      variables: {
        PULL_REQUEST_NAME: `${pullRequest.title}`,
        PULL_REQUEST_NUMBER: `${pullRequest.number}`,
        HEAD_COMMIT_SHA: `${pullRequest.head.sha}`,
        MERGE_COMMIT_SHA: `${pullRequest.merge_commit_sha}`,
        SOURCE_BRANCH_NAME: `${pullRequest.head.ref}`,
        SOURCE_BRANCH_SHA: `${pullRequest.head.sha}`,
        TARGET_BRANCH_NAME: `${pullRequest.base.ref}`,
        TARGET_BRANCH_SHA: `${pullRequest.base.sha}`
      }
    },
    json: true,
    url: gitlab.url
  },
  error => {
    if (error) {
      console.error(error)
      return
    }
  }
)
```

**Comment by jdalrymple** [comment]
Should be available in the latest next relese

**Comment by r1m** [comment]
I think we still have an issue when variable name contains mixed case : 
```js
variables: {
  TF_VAR_app_version: 'latest',
  TF_VAR_APP_TEST: 'latest',
}
```

results in 

```sh
TF_VAR_APP_TEST=latest
t_f__v_a_r_app_version=latest
```

**Comment by jdalrymple** [comment]
hmm true, easy fix, just need to change the regex to look for any capitalized characters.

**Comment by r1m** [comment]
I'm wondering : why do you need to decamelize keys ?

**Comment by jdalrymple** [comment]
Since it's JS, it allows users to pass in camelized variables. But since gitlab only takes in snake cased ( with the exception of variables like you're using), I had to make sure to decamelize

**Comment by jdalrymple** [comment]
Give it a look, should work for the majority of the use cases :)

**Comment by r1m** [comment]
This works for me 👍

**Comment by r1m** [comment]
After digging the API I found that the behaviour is different if you trigger a pipeline or create a new one.

### Trigger pipeline
You need first to create/retrieve a trigger token, then the variables should be given as a hash:

```ts
const options: BaseRequestOptions = {
      variables: {
        DEPLOY_ONLY: 'true',
        TF_VAR_app_version: version,
        TF_VAR_APP_TEST: version,
      }
    }
await this.api.Triggers.pipeline(project.id, refName, triggertoken, options)
```

![image](https://user-images.githubusercontent.com/137285/60959888-48079380-a309-11e9-8c6b-44bb7df193ac.png)

### Create a new pipeline
This will use your private token to create a pipeline
```ts
 const options: BaseRequestOptions = {
      variables: [
        { key: 'DEPLOY_ONLY', value: 'true' },
        { key: 'TF_VAR_app_version', value: version },
        { key: 'TF_VAR_APP_TEST', value: version },
      ]
    }
await this.api.Pipelines.create(project.id, refName, options)
```
This will result in a pipeline as you would create it on `/pipelines/new` gui.

These two requests are similar but not fully identical. The second one is working with current code base. The first one needs your changes.

If you send an hash to the first one -> BadRequest
If you send an array to the second one -> InternalError 😞

**Comment by jdalrymple** [comment]
Hmm, the second one should of always worked since the code i modified only affects the keys, not their values. 

As for the variable option, according to the gitlab api docs, the [second one](https://docs.gitlab.com/ee/api/pipelines.html#create-a-new-pipeline) only accepts an array, while the [first one only accepts a hash](https://github.com/python-gitlab/python-gitlab/issues/333#issuecomment-333851219). 

My change will only affect the first one (since its a hash, and i only look at keys).

Testing my changes in a playground: https://runkit.com/embed/l0rgf9hwqj2k

**Comment by r1m** [comment]
Agree, I was only documenting the behavior I encounter, since it's not really clear at first sight why we get badrequest or internal error.

Yes, our changes only affect the first one and it works for variables that matches my need.
It fails on something more exotic like 'mix_UP_name'. But that's another story and may be listed as a limitation in future doc.

Maybe a regex that filter out keys with 3 consecutive upper case letters will prevent this. It seems really odd to have a camel case name with 3 Upper letters (even 2 I would say)

I don't know the GL api enough to tell if there is another case where variables are passed this way.

-- Sylvain

________________________________

**Comment by jdalrymple** [comment]
I doubt such a variable would be used, but if it is well just change up the regex in the future!

**Comment by jdalrymple** [comment]
I'll release as soon as the test pasts. Getting a weird error rn :/

**Comment by r1m** [comment]
Thanks for your quick response and fix 👍
