### ISSUE TITLE
Can't use merge_when_pipeline_succeeds

### ISSUE THREAD

**Issue by timaschew** [jdalrymple/node-gitlab#256]
**Description**
Can't pass options when creating a merge request.  
(Creating the merge request itself does work!)

```
const mergeRequestOptions = {
  'merge_when_pipeline_succeeds': true,
  'should_remove_source_branch': true,
}
gitlabApi.MergeRequests.create(
        projectId,
        branchName,
        targetBranch,
        message,
        mergeRequestOptions
    )
```

I also tried already using `-` instead of `_`, like the python API is using but that didn't work as well.

**Steps to reproduce**
using `gitlabApi.MergeRequests.create` with the two options above.

I'm using a self hosted GitLab, version 11.6.3 (bc9391c), API v4

**Expected behaviour**
Open the merge request in the browser and see checkbox for remove source branch and enabled auto merge when pipeline succeeds.

**Actual behaviour**
Merge request is created but neither checkbox for remove source branch is checked nor it's marked as automerge when pipeline succeeds.

**Comment by jdalrymple** [comment]
Hey! I think this came up in the past hmm. Which version of the library are you using?

**Comment by timaschew** [comment]
Installed it today, it's 4.3.0

**Comment by timaschew** [comment]
You mean checking version 5.0.0-rc.8?

**Comment by casz** [comment]
Next is also a tag in npm for the latest version which I guess is rc 8 😊

**Comment by timaschew** [comment]
```javascript
// version 4.3.0
const gitlab = require('gitlab').default
const netrc = require('netrc-parser').default

const GITLAB_HOSTNAME = process.env.GITLAB_HOSTNAME
netrc.loadSync();

const token = netrc.machines[GITLAB_HOSTNAME].password

const gitlabApi = new gitlab({
    url: `https://${GITLAB_HOSTNAME}`,
    token: token,
});

console.log('>>>>>>>> token', token)

gitlabApi.MergeRequests.all('sdk/integration').then(console.log).catch(console.error)
```
Result: `... 928 more items ]`

In version 5 I cannot use `gitlab = require('gitlab').default` anymore, even without `.default`, so I switched to `ProjectsBundle`:

```javascript
// version 5.0.0-rc.8
const { ProjectsBundle } = require('gitlab')
const netrc = require('netrc-parser').default

const GITLAB_HOSTNAME = process.env.GITLAB_HOSTNAME
netrc.loadSync();

const token = netrc.machines[GITLAB_HOSTNAME].password

const gitlabApi = new ProjectsBundle({
    url: `https://${GITLAB_HOSTNAME}`,
    token: token,
});

console.log('>>>>>>>> token', token)

gitlabApi.MergeRequests.all('sdk/integration').then(console.log).catch(console.error)
```

Result: `HTTPError: Response code 404 (Not Found)`

So the auth doesn't work anymore.

**Comment by timaschew** [comment]
Thanks @casz I also have just realized that I was looking on the old README.md, I was expecting it's the new one.
Okay auth is working, but options are still not passed. I tried different styles:

```
            {
	    	'merge-when-pipeline-succeeds': true,
	    	'merge_when_pipeline_succeeds': true,
	    	'mergeWhenPipelineSucceeds': true
	    }
```

5th argument to `gitlabApi.MergeRequests.create`

**Comment by timaschew** [comment]
Okay found a solution:

- during creation you can only set `remove_source_branch`
- to auto merge you need to do a `gitlabApi.MergeRequests.accept` call there you can pass `merge_when_pipeline_succeeds`

Thanks for your help!
