### ISSUE TITLE
Typescript definitions missing

### ISSUE THREAD

**Issue by smnbbrv** [jdalrymple/node-gitlab#258]
Please make sure the new issue you are opening is not a duplicate, and **remove** this notice!

---

**Description**

The typings are not published. Why is #137 closed? How is it possible that TypeScript support issue is closed but there are no typings?

**Steps to reproduce**

```npm i gitlab```

**Expected behaviour**

The typings should be present (incl. the reference in package.json)

**Actual behaviour**

![image](https://user-images.githubusercontent.com/13453858/51901067-17651a80-23b7-11e9-95c0-e320e3831002.png)

**Possible fixes**
*(Any possible suggestions on how to fix this problem)*

**Comment by casz** [comment]
possible fix is `npm i gitlab@next` 😄

**Comment by jdalrymple** [comment]
@smnbbrv I updated the original issue to hopefully avoid anyone else wanting to hit their head in :rofl:

**Comment by smnbbrv** [comment]
:D thanks!
