### ISSUE TITLE
How can i get single project

### ISSUE THREAD

**Issue by rubyless** [jdalrymple/node-gitlab#260]
Get single project

GET /projects/:id

Parameters:

id (required) - The ID or NAMESPACE/PROJECT_NAME of a project

**Comment by thearabbit** [comment]
Excuse me @debanshu, Where you know this `Projects.show(id)`?
Where documentation? (I not found)

**Comment by debanshu** [comment]
@thearabbit I just found it in the source code originally. 
 https://github.com/jdalrymple/node-gitlab/blob/master/src/services/Projects.ts

Though, now with types it's far easier to get it as an ide autocompletion prompt.

**Comment by jdalrymple** [comment]
To get any singular resource, the API is the same: [resource].show(id) :)

**Comment by tmaly1980** [comment]
This really ought to be added to the documentation/README! All that covers is creating and paginating data. =(

**Comment by casz** [comment]
@tmaly1980 feel free to contribute :)

**Comment by jdalrymple** [comment]
@tmaly1980 I agree! Just need to find the time :(

**Comment by tmaly1980** [comment]
@casz I'm unfortunately new to this library and probably not the most suited to improve the documentation. But generally I'd say a practical review of the CRUD operations would be wise.

**Comment by lodi-g** [comment]
Well I'd say using the `show` keyword for the `GET` method is certainly not what I'd have chosen. Quite unclear on what it's doing.

**Comment by jdalrymple** [comment]
@lodi-g That's a fair argument. I was following the naming convention of the previous versions of this library. I didn't want to change it to much to avoid users having to do to much refactoring. 

GET: show
POST: create or add (depending on context)
PUT: edit
DELETE: remove

But yea for future versions, perhaps updating the commands to be a bit more intuitive could be done :)
