### ISSUE TITLE
mergerequests in next has incorrect url for approvers and needs put not post

### ISSUE THREAD

**Issue by jennparise** [jdalrymple/node-gitlab#262]
---
mergerequests in next has incorrect url for approvers and needs put not post
I have modified the code below and I can do a pull request if needed

**Steps to reproduce**
try to change approvers with api

**Expected behaviour**
the approvers should update

**Actual behaviour**
bad request

**Possible fixes**
```
approvers(
    projectId: ProjectId,
    approverIds: UserId[],
    approverGroupIds: GroupId[],
    { mergerequestIId, ...options }: { mergerequestIId: MergeRequestId } & BaseRequestOptions,
  ) {
    const [pId, mIId] = [projectId, mergerequestIId].map(encodeURIComponent);

    let url;

    if (mergerequestIId) {
      url = `projects/${pId}/merge_requests/${mIId}/approvers`;
    } else {
      url = `projects/${pId}/approvers`;
    }

    return RequestHelper.put(this, url, { approverIds, approverGroupIds, ...options });
  }
```

**Comment by jdalrymple** [comment]
Ill look into this at the end of this week!

**Comment by jdalrymple** [comment]
Updated in the latest next release

**Comment by jennparise** [comment]
I see you updated the http method, but I believe this still needs to be updated: 
From: 
    if (mergerequestIId) {
      url = `projects/${pId}/merge_requests/${mIId}/approvals`;
    } else {
      url = `projects/${pId}/approvals`;
    }

To:
    if (mergerequestIId) {
      url = `projects/${pId}/merge_requests/${mIId}/approvers`;
    } else {
      url = `projects/${pId}/approvers`;
    }

**Comment by jdalrymple** [comment]
Fixed! :)
