### ISSUE TITLE
Repositories tree

### ISSUE THREAD

**Issue by Aviortheking** [jdalrymple/node-gitlab#266]
**Description**
*(Brief description of your issue here)*

When i use my script under on electron the first time I don't get anything and after i click a second time 

(Paste any relevant logs - please use code blocks (```) to format console output,
logs, and code as it's very hard to read otherwise.)

simple test (.tar.gz with my current project)
```js
Gitlab = require('gitlab/dist/es5').default;

options = {
	url: 'https://gitlab.com',
	token: 'tokenHere'
}

projectId = 123456;

gitlab = new Gitlab(options);


document.querySelector(".button").addEventListener("click", buttonClick);

buttonClick = async function() {
    console.log("test1");
    var tet = await test()
    console.log(tet);
}

test = async function() {
    return await gitlab.Repositories.tree(projectId, {recursive: true});
}



```

first time logs
```
test1
```

second time
```
test1
object {ect,etc}
```

**Steps to reproduce**
*(Tell us how to reproduce this issue. Please provide a working demo, you can use this template as a base)*

[electron-quick-start.tar.gz](https://github.com/jdalrymple/node-gitlab/files/2871016/electron-quick-start.tar.gz)

- decompress the project
- add your token in the src/renderer.coffee
- build the project
- launch it
- open the console (CTRL + SHIFT + I)
- click on a project in the list
- see the console updating nothing nor the UI not updating the tree view
- click on another project and see if the ui update itself

**Expected behaviour**
*(What is supposed to happen?)*

- we should always get an object

**Actual behaviour**
*(What happens instead?)*

- we don't get the first one 
- we get it on the the first one on the second click (even if it's an other projectid)
- on the second click w get the second one tree

**Possible fixes**
*(Any possible suggestions on how to fix this problem)*

idk

**Comment by casz** [comment]
you have an async function that you do not await the result for.

**Comment by Aviorleking** [comment]
Oups juste an error while pasting my test

**Comment by jdalrymple** [comment]
Ill look into this at the end of this week

**Comment by jdalrymple** [comment]
Could you test this with the next version of the library? the code to get the tree is very basic so im unsure as to why it would be causing problems.

**Comment by jdalrymple** [comment]
Fixed in the next build!
