### ISSUE TITLE
The Lint api has been moved from /lint to /ci/lint

### ISSUE THREAD

**Issue by LRH539** [jdalrymple/node-gitlab#277]
**Description**
*Lint API has been moved from /lint to /ci/lint (this is not reflected in official Gitlab docs).*

**Steps to reproduce**
*Post /api/v4/lint retrieves 404, Post /api/v4/ci/lint retrieves content missing.*

**Expected behaviour**
*The Lint service can be used to validate .gitlab-ci.yml files.*

**Actual behaviour**
*Using the Lint service results in a 404.*

**Possible fixes**
*This can be fixed, by simply changing the path in the Lint module, I will open a PR for this and reference this issue.*

**Comment by casz** [comment]
I wonder which version this was changed in?
