### ISSUE TITLE
Failed to execute 'fetch' on 'Window' on Next version

### ISSUE THREAD

**Issue by patrickalima98** [jdalrymple/node-gitlab#282]
**Description**
When using the node-gitlab module the xmlHttpRequest request is not working, it displays the following error

**Steps to reproduce**

To Reproduce
1- Create a new Vue.js application with TypeScript
2- Install gitlab with `npm install gitlab@next`
3- Import gitlab with `const {Gitlab} = require('gitlab');` on src/App.vue
4- Start a new connection:

```js
// Instantiating
const api = new Gitlab({
  token: 'abcdefghij123456',	// Can be created in your profile.
  useXMLHttpRequest: true
})
```
5- Call a Api:
```js
api.Projects.all({ maxPages: 1, perPage: 40 }).then(data => {
  console.log(data);
});
```

5- Start serve with `npm run serve`
6- Check console on devtools

**Expected behavior**
A json return with 40 projects

![image](https://user-images.githubusercontent.com/17622137/53903790-5e33d900-4023-11e9-8551-4f0f8b78b408.png)

**Environment**
 - OS and version: Windows 10
 - node version: 11.4.0
 - npm version: 6.4.1
 - vue-cli-plugin-electron-builder version : 1.0.0
 - electron version: 4.0.4
- node-gitlab: @next
- Firefox Developer Edition: 66
- Chrome: 72

I'm are using Electron for my project, but this error is present on my all browsers Firefox And Chrome,
please check my [Electron demo repository](https://github.com/patrickalima98/gitlab-electron-vue) or my [Browser demo repository](https://github.com/patrickalima98/gitlab-test-vue)

Any ideia how to fix this?

**Comment by jdalrymple** [comment]
Currently working on fixing the xhr compatibility! Will keep you updated

**Comment by patrickalima98** [comment]
@jdalrymple thank you, I'll wait

**Comment by jdalrymple** [comment]
I tested with the electron version, seems to work fine:

```
const api = new Gitlab({
  token: 'abcdefghij123456',	// Can be created in your profile.
})

api.Projects.all({ maxPages: 1, perPage: 40 }).then(data => {
  console.log(data);
});
```
