### ISSUE TITLE
MergeRequests: approve method requires sha parameter

### ISSUE THREAD

**Issue by buffcode** [jdalrymple/node-gitlab#290]
The method `MergeRequests.approve` in `next` requires the existence of the `sha` parameter.

This [parameter must be optional](https://docs.gitlab.com/ee/api/merge_request_approvals.html#approve-merge-request).

**Steps to reproduce**

```ts
import Gitlab from "gitlab";

const api = new Gitlab.MergeRequests({});

api.approve(1, 2);
// or
api.approve(1, 2, {});
```

**Expected behaviour**
- No TypeScript errors

**Actual behaviour**
```
Error:(251, 13) TS2554: Expected 3 arguments, but got 2.
```
or
```
Error:(251, 54) TS2345: Argument of type '{}' is not assignable to parameter of type '{ sha: string; } & BaseRequestOptions'.
  Property 'sha' is missing in type '{}' but required in type '{ sha: string; }'.
```

**Comment by jdalrymple** [comment]
I definitely overlooked that
