### ISSUE TITLE
Cannot use pagination options in request

### ISSUE THREAD

**Issue by Fleuh** [jdalrymple/node-gitlab#293]
Hey guys.

First awesome work on this package ! 

Got a little question tho. I am tryin to use pagination in one of my calls. But it looks like it does not work, so I am wondering if i am not doing something wrong.

Here is a portion of my source code
```
let service = new GitLab({
    url: <myGitlabAddress>,
    token: <myToken>,
})
let res = await service.Pipelines.all(project.id, {
                        ref: branch.name,
                        perPage: 1,
                    })
```

But instead of getting only one result, i am receiving all the pipelines in my projects. What am i doing wrong ?

EDIT : I tried to request through postman and i am receiving only one pipeline with the paramater `per_page=1`

Thanks for your time !

**Comment by casz** [comment]
https://github.com/jdalrymple/node-gitlab/blob/master/src/infrastructure/RequestHelper.ts#L23-L25

Use `maxPage` together with `perPage`

**Comment by Fleuh** [comment]
Thank you, working fine.
Cya :)
