### ISSUE TITLE
addTimeEstimate for merge request calls wrong endpoint

### ISSUE THREAD

**Issue by aol-nnov** [jdalrymple/node-gitlab#296]
https://github.com/jdalrymple/node-gitlab/blob/master/src/services/MergeRequests.ts#L70

should be `projects/${pId}/merge_requests/${mId}/time_estimate`, not `projects/${pId}/issues/${mId}/time_estimate`

corresponding docs: https://docs.gitlab.com/ee/api/merge_requests.html#set-a-time-estimate-for-a-merge-request

**Comment by jdalrymple** [comment]
Fixed in next. If you REALLY needed it in master, just reopen :)
