### ISSUE TITLE
The requested module 'gitlab' does not provide an export named 'Gitlab'

### ISSUE THREAD

**Issue by aol-nnov** [jdalrymple/node-gitlab#302]
```
npm init
npm install --save gitlab@next
```

cat index.mjs

```
import { Gitlab } from 'gitlab';
```

```
node --experimental-modules index.mjs 
SyntaxError: The requested module 'gitlab' does not provide an export named 'Gitlab'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:80:21)
```

```
node -v
v10.6.0
```

but documentation on the `next` branch reads as 
```
// ES6 (>=node 10.0.0)
import { Gitlab } from 'gitlab';
```

What am I missing?

**Comment by jdalrymple** [comment]
Thats a problem with the experimental mjs support. It doesn't seem to support named exports.  If you do:

```
import GitlabAPI from 'gitlab'

let {Gitlab} = GitlabAPI
```

**Comment by aol-nnov** [comment]
@jdalrymple , thanks for the hints!

Also, I'd like to mention, that the following docs snippet from `next`

```
// ES5, assuming native or polyfilled Promise is available
const Gitlab = require('gitlab')


// Instantiating
const api = new Gitlab({
```

gives `TypeError: Gitlab is not a constructor` too

**Comment by jdalrymple** [comment]
@aol-nnov Fixed! Sorry about that.

**Comment by mariooc** [comment]
help, 
not work
try npm install --save gitlab@next
![gitlab-node](https://user-images.githubusercontent.com/2160877/56663730-250c0280-667d-11e9-96d2-24864f4dcfa5.png)

and  npm install --save gitlab
![gitlab-2](https://user-images.githubusercontent.com/2160877/56663959-9c419680-667d-11e9-8177-352099fea4ff.png)

**Comment by jdalrymple** [comment]
Hmm, I think you can't install the package in a module with the same name.

**Comment by casdevs** [comment]
Getting back to this...
I'm using gitlab@11.1.2 with a node.js v12 project and `--experimental-modules` switched on.

```import {Gitlab} from 'gitlab';``` gives me ```The requested module 'gitlab' does not provide an export named 'Gitlab'```.

However, when I remove ```"type": "module"``` from your module's package.json file, everything works as expected.

This statement was introduced somewhere between 11.0.0 (here, everything works as expected) and 11.1.2.

I'm not super familiar with the ES6 vs. CommonJS package interoperability details, but shouldn't you use ```"type": "module"``` only when your ```"main"``` export is based on ES6 import/export?

Maybe you can re-open this issue?

Thanks & best regards
Stefan

**Comment by casdevs** [comment]
see https://github.com/jdalrymple/node-gitlab/blame/master/package.json#L104

**Comment by paulrobertlloyd** [comment]
I think I may be seeing the same issue as @casdevs. I’m importing the package using the CommonJS syntax:

```
const {Gitlab} = require('gitlab');
```

This works fine for me locally (using Node v12), and when I run my tests remotely using Node v10 (via a GitHab Actions workflow). However, running tests against this code using Node v12, I get the following error:

```
Error (NodeError) {
290
    message: 'Must use import to load ES Module: /home/runner/work/indiekit/indiekit/packages/publisher-gitlab/node_modules/gitlab/dist/index.js',
291
  }
```

Note that this error is pointing to index.js, which uses CommonJS modules, yet Node thinks it’s an ES Module. Which makes me think @casdevs is right when he says:

> I'm not super familiar with the ES6 vs. CommonJS package interoperability details, but shouldn't you use `"type": "module"` only when your `"main"` export is based on ES6 import/export?

Hope this helps!

**Comment by casdevs** [comment]
thanks for your feedback, @paulrobertlloyd 

@jdalrymple: Maybe you can re-open this issue? I could also provide a pull request if required.
