### ISSUE TITLE
Failed to unshare group from a project

### ISSUE THREAD

**Issue by sjarrossay** [jdalrymple/node-gitlab#303]
**Description**

When I call Project.unshare, nothing append 

**Steps to reproduce**
Share a group to a project
Call Projects.unshare to remove this link, nothing append

**Expected behaviour**
deleted link

**Actual behaviour**
NA

**Possible fixes**
path built is `"projects/" + idProject + "/share" + idGroup`
 in place of `"projects/" + idProject + "/share/" + idGroup`

**Comment by jdalrymple** [comment]
Fixed and released!
