### ISSUE TITLE
GroupIssues

### ISSUE THREAD

**Issue by klorenzen7** [jdalrymple/node-gitlab#306]
My team uses Group boards extensively and I would like to filter on issues in projects within a group. We don’t have the Epics option so using the Group Issues API would be best. This would be similar to the EpcIssues API already supported by node-gitlab.

**Comment by jdalrymple** [comment]
The only group issue specific api is to get all the group issues. Is this what you are looking for ? https://docs.gitlab.com/ee/api/issues.html#list-group-issues

**Comment by klorenzen7** [comment]
Yes, I would like to use that api. We roll up our issues to a group board so pulling issues by group is the best way for me to work with them. Other apis would let me pull issues by user but then I can not filter by group. GET /groups/:id/issues?labels=doing would be great. :-)
