### ISSUE TITLE
Typescript definitions of 4.5.1 are broken

### ISSUE THREAD

**Issue by DanielRose** [jdalrymple/node-gitlab#308]
**Description**

In release 4.5.1, the Typescript definition files are included (#294). However, the definition files are broken, because they implicitly include `types.d.ts`, which is not part of the npm package. As a result, compiling a Typescript file which includes the gitlab package results in many compile errors.

**Steps to reproduce**
```
// test.ts
import Gitlab from "gitlab";

$ tsc
```

**Expected behaviour**

Compile success.

**Actual behaviour**

```
$ tsc
node_modules/gitlab/dist/latest/infrastructure/RequestHelper.d.ts(11,16): error TS2304: Cannot find name 'temporaryAny'.
node_modules/gitlab/dist/latest/infrastructure/RequestHelper.d.ts(27,12): error TS2304: Cannot find name 'temporaryAny'.
node_modules/gitlab/dist/latest/infrastructure/RequestHelper.d.ts(48,14): error TS2304: Cannot find name 'temporaryAny'.
...
node_modules/gitlab/dist/latest/templates/ResourceVariables.d.ts(9,22): error TS2304: Cannot find name 'ResourceId'.
node_modules/gitlab/dist/latest/templates/ResourceVariables.d.ts(10,22): error TS2304: Cannot find name 'ResourceId'.
node_modules/gitlab/dist/latest/templates/ResourceVariables.d.ts(11,24): error TS2304: Cannot find name 'ResourceId'.
```

(343 errors)

**Possible fixes**

Include types.d.ts in the npm package, or explicitly reference the various "base" types.

The latter fix is done in the 5.0 prerelease BTW.

**Comment by jdalrymple** [comment]
I probably wont tackle this one since 5.0.0 is so close to being completed. No point in redoing work :(

**Comment by jdalrymple** [comment]
@centigrade-thomas-becker Yup! We are looking into it. See #321 for the latest updates
