### ISSUE TITLE
5.0.0-rc.14: Pagination is broken

### ISSUE THREAD

**Issue by haggholm** [jdalrymple/node-gitlab#311]
**Description**

Listing projects with pagination no longer works. `gitlab.Projects.all({ perPage: 100, maxPages: 100 })` returns all projects from our Gitlab instance with 5.0.0-rc.13, but only 100 with 5.0.0-rc.14.

**Comment by jdalrymple** [comment]
Looking now, thanks! Not sure how the tests didn't catch this 🤔

**Comment by jdalrymple** [comment]
Found the problem!

**Comment by jdalrymple** [comment]
Just released the fix! Give it a look when you have a chance
