### ISSUE TITLE
Impossible to pass variables when triggering a pipeline

### ISSUE THREAD

**Issue by MaximeCheramy** [jdalrymple/node-gitlab#314]
**Description**

The Triggers.pipeline function allows to pass options but it looks like it's not possible to pass variables. Actually the bug looks a lot like https://github.com/jdalrymple/node-gitlab/issues/254 but for Triggers.pipeline.

**Possible fixes**

My workaround is to do a POST request myself and pass the data as 'form' instead of json:

```js
  return requestPromise({
    method: 'POST',
    uri: `${baseUrl}/projects/${projectId}/trigger/pipeline`,
    form: {
      ...options
    }
  })
```

I suppose the fix is just adding `true` here: https://github.com/jdalrymple/node-gitlab/blob/master/src/services/Triggers.ts#L43 but I haven't took the time to test it.

**Comment by jdalrymple** [comment]
Ill give it a look!

**Comment by jdalrymple** [comment]
I think this should be ok in the next build. Give it a look when you have a chance!

**Comment by neacao** [comment]
Seems like this issue is not fixed !!

**Comment by jdalrymple** [comment]
Ill give it a look when i get the chance.

**Comment by jdalrymple** [comment]
Oh true it s a form not a body object. Will fix

**Comment by neacao** [comment]
Thanks @jdalrymple , hope this fix will available soon
