### ISSUE TITLE
type missed

### ISSUE THREAD

**Issue by bluelovers** [jdalrymple/node-gitlab#318]
**Description**

```
{
  "name": "gitlab",
  "version": "4.5.1",
```

miss `ProjectId` in `MergeRequests.d.ts`

![image](https://user-images.githubusercontent.com/167966/58362525-6b49c100-7eca-11e9-8925-715382b91f82.png)

**Steps to reproduce**

**Expected behaviour**

**Actual behaviour**

**Possible fixes**

**Comment by jdalrymple** [comment]
This is fixed in the upcoming version :)
