### ISSUE TITLE
node-gitlab tries parsing the result of downloadTraceFile() as JSON

### ISSUE THREAD

**Issue by alippai** [jdalrymple/node-gitlab#320]
Calling downloadTraceFile() results in `FetchError: invalid json response body at` after upgrading to version 5

**Comment by jdalrymple** [comment]
I'll look into it today :(

**Comment by alippai** [comment]
This is a really nice project, keep up the good work ;)

**Comment by jdalrymple** [comment]
@alippai Where you trying to use the streamed response, or the plain JSON

**Comment by alippai** [comment]
Imported the ProjectsBundle, instantiated as `services`, then called `services.Jobs.downloadTraceFile(PROJECT_ID, jobId)`

**Comment by jdalrymple** [comment]
Spent some time on this last night, but wasn't able to narrow it down. Ill try again tonight and hopefully figure it out.

**Comment by yys-grab** [comment]
`service.RepositoryFiles.remove(ProjectId, filePath, branch, options)` also giving `FetchError: invalid json response body at` error as well when request success.

**Comment by jdalrymple** [comment]
@yys-grab Yea im modifying it right now. im trying to validate the type of response before processing it

**Comment by jdalrymple** [comment]
@yys-grab The repofiles problem should be fixed as well :)
