### ISSUE TITLE
Cannot find type definition file for various files

### ISSUE THREAD

**Issue by patrickalima98** [jdalrymple/node-gitlab#329]
**Description**
I'm trying use this module on my project with Electron, Vue and Typescript. But after import, the Typescript compiler show various erros about type files, see the image:

![image](https://user-images.githubusercontent.com/17622137/58842908-a4123480-8646-11e9-807f-edac02ec7433.png)

My App.vue:

```html
<script lang="ts">
import { Component, Vue } from 'vue-property-decorator';
import HelloWorld from './components/HelloWorld.vue';
import { Gitlab } from 'gitlab';

@Component({
  components: {
    HelloWorld,
  },
})
export default class App extends Vue {}
</script>
```
My packahe.json:
```json
{
  "name": "demo-gitlab",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "serve": "vue-cli-service serve",
    "build": "vue-cli-service build",
    "lint": "vue-cli-service lint",
    "electron:build": "vue-cli-service electron:build",
    "electron:serve": "vue-cli-service electron:serve",
    "postinstall": "electron-builder install-app-deps",
    "postuninstall": "electron-builder install-app-deps"
  },
  "dependencies": {
    "gitlab": "^6.0.0",
    "vue": "^2.6.10",
    "vue-class-component": "^7.0.2",
    "vue-property-decorator": "^8.1.0"
  },
  "devDependencies": {
    "@vue/cli-plugin-typescript": "^3.8.0",
    "@vue/cli-service": "^3.8.0",
    "electron": "^5.0.0",
    "node-sass": "^4.9.0",
    "sass-loader": "^7.1.0",
    "typescript": "^3.4.3",
    "vue-cli-plugin-electron-builder": "^1.3.4",
    "vue-template-compiler": "^2.6.10"
  },
  "main": "background.js"
}

```
**Steps to reproduce**

Clone my repo demo:
`
git clone https://github.com/patrickalima98/demo-gitlab.git
`

Install dependencies
`npm i `

Run:

`
npm run electron:serve
`

See erros in your terminal/cmd

I'm trying to fix this problem for several hours, but to no avail.
Thanks everyone for the help :)

**Comment by jdalrymple** [comment]
Hmm, anything stand out to you @rkrasiuk. You've had better luck than both me and @casz 🤣

**Comment by rkrasiuk** [comment]
@jdalrymple you've published v6 manually?

**Comment by jdalrymple** [comment]
Nope, went through semantic release :/

**Comment by rkrasiuk** [comment]
my local build includes triple slash directive only into the top level `index.d.ts`. you might want to check in what result your version of compiler produces

**Comment by jdalrymple** [comment]
So i checked the build files. It still only exists in the top level index.d.ts...so im confused

**Comment by jdalrymple** [comment]
But in the released package its there. WEIRD

**Comment by jdalrymple** [comment]
Furthermore, IIt looks like without the correct tripple slash command in those other files, many of the types are undefined such as ProjectId ? Unless im missing something locally? Do you experience this @casz @rkrasiuk ?

**Comment by mrozado** [comment]
I'm having the same issue

**Comment by jdalrymple** [comment]
Yea Still trying to figure out why the build process added the extra /// references.

**Comment by jdalrymple** [comment]
Any new ideas as to this problem?

**Comment by DanielRose** [comment]
The problem is that Typescript type definitions work a bit differently than what you are trying to do here:

The /// references are used for including additional type definitions for modules which are not directly referenced. That is why the compiler is adding them to all compiled files.

When working in the project, everything works because the `typings` directory (and the type definiton files in them) is included as part of the project. However, since the type definitions are used without a namespace, they are polluting the global namespace. However, you definitely don't want to have that in the final build output.

The correct way to solve this is by removing the typings directory, adding the various definitions to somewhere else in the source directory, and explicitly importing the used types. I'm currently working on fixing that and will send a PR when done.

**Comment by sjarrossay** [comment]
I have same problem, 
to not be blocked by this I copy/past typings folder in dist folder, dirt solution I agree.
but there is another problem at the and of all typings

```
node_modules/gitlab/typings/globals.d.ts:4:15 - error TS2304: Cannot find name 'URL'.

4   URL: typeof URL,
                ~~~
node_modules/gitlab/typings/globals.d.ts:5:27 - error TS2304: Cannot find name 'URLSearchParams'.
5   URLSearchParams: typeof URLSearchParams,
                            ~~~~~~~~~~~~~~~
node_modules/gitlab/typings/infrastructure.d.ts:51:19 - error TS2304: Cannot find name 'FormData'.
51   body?: object | FormData;
```

**Comment by DanielRose** [comment]
@sjarrossay Those types are part of the DOM. Your consuming project needs to include the dom library. Normally this is done by adding "dom" to the "lib" section of your `tsconfig.json`, for example:

```json
{
  "compilerOptions": {
    "lib": [ "es2015", "dom" ]
  }
}
```

**Comment by sjarrossay** [comment]
Fine thx
