### ISSUE TITLE
Pipelines.showJobs() options should be optional

### ISSUE THREAD

**Issue by scottboyd-ai** [jdalrymple/node-gitlab#336]
When calling Pipelines.showJobs(), the options parameter is required. This allows a user to filter the jobs returned by their status. However, if the user wants to return all jobs regardless of status, there is no way to do this without modifying the function declaration to have options as an optional argument.

**Steps to reproduce**

Call Pipelines.showJobs() with project Id and pipeline Id specified. A third parameter is required.

**Expected behaviour**
This third parameter should be optional.

**Actual behaviour**
This third parameter is required. Setting the value to null causes an error. Setting the value to {scope: null} causes an error. Setting the value to {scope: 'created'|| 'pending' || 'running'  || 'failed'  || 'success'  || 'canceled'  || 'skipped'  || 'manual'} allows the user to access all jobs regardless of status.

**Possible fixes**
Modify showJobs to have options as an optional parameter.

**Comment by jdalrymple** [comment]
I agree! I must of missed this !

**Comment by jdalrymple** [comment]
Easy fix! Should be out today
