### ISSUE TITLE
ResouceDiscussions.addNote is wrong

### ISSUE THREAD

**Issue by ianliu** [jdalrymple/node-gitlab#342]
**Description**
By inspecting the Gitlab API page [Discussions | Add note to existing issue discussion](https://docs.gitlab.com/ee/api/discussions.html#add-note-to-existing-issue-discussion), I can see that the method [ResourceDiscussions.addNote](https://github.com/jdalrymple/node-gitlab/blob/master/src/templates/ResourceDiscussions.ts#L16) isn't right. It is calling a `PUT`, while the endpoint expects a `POST`.

Also, the Documentation isn't very clear, but I think you can call it in the following two ways:

 * `POST /projects/:id/issues/:issue_iid/discussions/:discussion_id/notes` to append a new note into a discussion;
 * `POST /projects/:id/issues/:issue_iid/discussions/:note_id/notes` to "transform" a note into a discussion, whilst appending a new note into it.

**Comment by jdalrymple** [comment]
Ill fix this in the next day! Sorry about that :s

**Comment by ianliu** [comment]
@jdalrymple thanks! :tada:
