### ISSUE TITLE
Cannot read property json of undefined when removing a hook

### ISSUE THREAD

**Issue by gvso** [jdalrymple/node-gitlab#343]
**Description**

I'm trying to remove a webhook from my application, which is correctly removed on GitLab, but the promise is rejected anyways with the error:

```
TypeError: Cannot read property 'json' of undefined
at Object.<anonymous> (node_modules/gitlab/dist/index.js:1:6496)
at node_modules/gitlab/dist/index.js:1:2516
at Object.throw (node_modules/gitlab/dist/index.js:1:2621)
at p (node_modules/gitlab/dist/index.js:1:1433)
at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Steps to reproduce**
This the code I'm using to remove hooks. `api` has been defined in my class:
```
this.api.ProjectHooks.remove(projectId, hookId)
    .then(result => {
      // Never gets here even though hook is successfully deleted on GitLab.
      doSomething(result)
    })
    .catch(err => {
     // The above error is printed
      console.log(err);

      if (err.response && err.response.status == 404) {
        // If we get a 404 then it doesn't exist, so we don't need to remove it.
        return doSomething(null);
      }

      log.error({repo: repo}, 'Problem removing GitLab hook');

      return doSomethingElse();
    });
```

Is there something I'm doing wrong or is this an issue with the project?

**Comment by jdalrymple** [comment]
Hmm looks good. I think the error may have to do with the response / error handling. To make sure the errors don't get swallowed, we added a catch to output them properly but it could be causing this problem. 

To figure it out id check to see if an error is being thrown in that try catch, and go from there. Ill try and get around to this at some point in the week :)

**Comment by jdalrymple** [comment]
I added this change in this recent branch. Hopefully it helps with the error handling

**Comment by jdalrymple** [comment]
Follow up if you still run into the same problem :)

**Comment by gvso** [comment]
Thanks for the quick reply! That seems to solve the previous issue, but it's creating a new one:

```
TypeError: Cannot read property 'includes' of null
at node_modules/gitlab/dist/index.js:1:5949
at node_modules/gitlab/dist/index.js:1:2516
at Object.next (node_modules/gitlab/dist/index.js:1:2621)
at i (node_modules/gitlab/dist/index.js:1:1382)
at processTicksAndRejections (internal/process/task_queues.js:89:5)
```

**Comment by jdalrymple** [comment]
Oh no, hmm.

I think thats from line 41 from the KyRequester, but that cant be correct. All responses should contain the content-type :s

**Comment by jdalrymple** [comment]
Hopefully this one fixes that edge case 🤞

**Comment by gvso** [comment]
Yes, this solved the issue. Thank you so much!
