### ISSUE TITLE
Wrong URL for some groups

### ISSUE THREAD

**Issue by sjarrossay** [jdalrymple/node-gitlab#344]
When I call GroupsBundle.GroupMembers.all
For some group id, I got an error 404 with this URL built :
`url:"https://gitlab.xxx.xx/api/v4/groups/groups/593/members?id=593&page=2&per_page=20"url:"https://gitlab.xxx.xx/api/v4/groups/groups/593/members?id=593&page=2&per_page=20"`

for exemple this call
this.groups.GroupMembers.all(593,false)

**Comment by jdalrymple** [comment]
Hmm, which version of the library are you using?

**Comment by sjarrossay** [comment]
The last : 6.3.0

It's very strange error is made always with the same id, if I take 600 for exemple or return good results.

**Comment by jdalrymple** [comment]
That's really odd. I'll give it a look!

**Comment by obartra** [comment]
I'm getting similar issues with `/api/v4/projects/projects/:slug/merge_requests/:iid/notes`

**Comment by jdalrymple** [comment]
Ill check them out at the same time

**Comment by jdalrymple** [comment]
Found the problem, latest push should handle this :)

**Comment by obartra** [comment]
Hey thanks for the super fast turn around on this!

It could be my setup but I just ran it locally and I'm getting this error instead:

```
Error: `input` must not begin with a slash when using `prefixUrl`
    at new Ky (/~/repos/node-gitlab/node_modules/ky/umd.js:182:11)
```

**Comment by jdalrymple** [comment]
Yup found it!

**Comment by jdalrymple** [comment]
Give that a try :)

**Comment by obartra** [comment]
Hey I'm not seeing the commit to pull, did you push it somewhere else?

**Comment by jdalrymple** [comment]
Its in the 344-pagination branch. Should be there: https://github.com/jdalrymple/node-gitlab/commit/38d50dc6e8b3d4ee91888bdb6489bed5f7d145dc

**Comment by obartra** [comment]
💥 yeah that was it, it's working now

![](https://media.giphy.com/media/l2Sqir5ZxfoS27EvS/giphy.gif)

**Comment by sjarrossay** [comment]
Thx my Lord

**Comment by sjarrossay** [comment]
Arf with this new version I have this issue
When I call 

```
            this.api = new Gitlab(configGitlab);
            res = await (this.api.Users as Users).events(user.id, option) as Event[];
```
I receive an error with this URL :

> https://gitlab.xxx.xxx/api/v4/https://gitlab.xxx.xxx/api/v4/users/520/events?action=pushed&after=2019-06-02&before=2019-06-09&id=520&page=2&per_page=20&sort=desc

Do I create new issue ?

**Comment by jdalrymple** [comment]
Hmm, that would be the same problem. Which version number?

**Comment by casz** [comment]
his using host with `http://` (or perhaps without protocol) most likely and his host returns `https://` :laughing: 
That's why the replace regex was there in the first place :laughing:

Perhaps @sjarrossay you could fix your gitlab config?

**Comment by jdalrymple** [comment]
Lmao you're right. That's exactly why we did that. I'll fix the regex today then

**Comment by casz** [comment]
or perhaps his host returns a different hostname, he did just type `.xxx.xxx` :cry: 

protip put the link in in backticks `` `https://gitlab.xxx.xxx/api/v4/https://gitlab.xxx.xxx/api/v4/users/520/events?action=pushed&after=2019-06-02&before=2019-06-09&id=520&page=2&per_page=20&sort=desc`

**Comment by casz** [comment]
to a human, these URL looks the same but again the URL has been "sanitized" for a very secret URL :scream:

**Comment by sjarrossay** [comment]
That's ;) It's my secret garden

**Comment by sjarrossay** [comment]
I replace my hostname by xxx.xx
The response of bundle give me the real url

**Comment by casz** [comment]
Why do you do the replacement, if I may ask? :cry:

**Comment by jdalrymple** [comment]
So they dont have post their hostname on github lol?

**Comment by casz** [comment]
nono, as I understood him his doing hostname replacement. So inside his hosts file his using one hostname for his gitlab server but the gitlab instance returns him another :laughing:

**Comment by jdalrymple** [comment]
I think the only way I can fix this is by putting back the regex, but include the custom url token that may of been added when a service is initialized.

ie. if this.url = http://gitlab.com/api/v1/orders

then the replace has to be for /.+\/api\/v\d\/orders/

Why is it that the host string isnt https to begin with if the pagination links are asking for https?

**Comment by casz** [comment]
Perhaps do nothing? @sjarrossay is a special case :cry:

**Comment by jdalrymple** [comment]
Would it ever be the case that your host would be different then the pagination url? If they should be the same security, I could just throw an error?

**Comment by sjarrossay** [comment]
@casz to be clear : there is no problem about hostname of my gitlab server.
host give me the good one.

**Comment by jdalrymple** [comment]
Yea the http one may work just fine, but if gitlab returns https, shouldnt the https prefix be used in the hostname instead?

**Comment by sjarrossay** [comment]
If you ask about hostname in conf yes https is used.
With previous version, I never see this issue

**Comment by casz** [comment]
Hopefully, 6.3.7 should fix your issue @sjarrossay

**Comment by sjarrossay** [comment]
Yeah lot of thanks, i try it tomorrow

**Comment by sjarrossay** [comment]
Tested, just one word : perfect
