### ISSUE TITLE
Ky process does not exit

### ISSUE THREAD

**Issue by jamime** [jdalrymple/node-gitlab#348]
I have found when using node-gitlab within danger the node process does not exit, this is a bug in [ky](https://github.com/sindresorhus/ky/issues/138).

After, reviewing the `ky` and `ky-universal` package, it [recommends using got](https://github.com/sindresorhus/ky-universal) if you only intend on supporting node.
I suggest that we heed their advice and migrate to the [got package](https://www.npmjs.com/package/got) which will alleviate this issue.

**Comment by jdalrymple** [comment]
We switched to Ky to allow for a browser compatible version. Got does not allow for this, that's why we're using ky-universal

**Comment by Ivaylo-Lafchiev** [comment]
Is this being looked at? 
Is there any custom requester that's currently supported that doesn't exhibit this behavior? In fact, what custom requesters _are_ supported, as the docs don't make that clear?

**Comment by jdalrymple** [comment]
Just waiting for the PR to be merged: https://github.com/sindresorhus/ky/pull/145

Currently no, though it would be really easy to create a custom requester using got that wouldn't have this problem. Thought with the PR basically at the end of its review, it seemed like overkill to do that. The custom requester can be ANY request library, but should follow the same request options/response structure as seen in the KyRequester.ts file :)

**Comment by Ivaylo-Lafchiev** [comment]
Gotcha, thanks for clarifying.

**Comment by centigrade-thomas-becker** [comment]
Can someone please tell me which older version of node-gitlab does not exhibit this behaviour?

**Comment by jdalrymple** [comment]
The last release of 4.x I believe, so 4.5.1?

**Comment by centigrade-thomas-becker** [comment]
I have tried some newer versions and 8.0.0 worked for me.

**Comment by tiger-seo** [comment]
@jdalrymple the fix in Ky has been merged https://github.com/sindresorhus/ky/releases/tag/v0.11.2

**Comment by jdalrymple** [comment]
@centigrade-thomas-becker Thats good, but weird lol I guess the timeout behaviour was added to ky more recently?

**Comment by awgeorge** [comment]
Supposedly, it was a regression. So an older version may very well work. @jdalrymple, when you're able to make a patch release, I'll update https://github.com/danger/danger-js/issues/875. Thanks.
