### ISSUE TITLE
Merge Request pipelines URL host is duplicated in request

### ISSUE THREAD

**Issue by scottboyd-ai** [jdalrymple/node-gitlab#352]
**Description**

When calling MergeRequests.pipelines(), the url of the get request has the host url duplicated.

It returns the following 404:

{ HTTPError: Not Found
    at fn (C:\dev\gitlab-tool\node_modules\ky\umd.js:242:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
  name: 'HTTPError',
  response: 
   Response {
     size: 0,
     timeout: 0,
     [Symbol(Body internals)]: { body: [Object], disturbed: true, error: null },
     [Symbol(Response internals)]: 
      { url: 'https://gitlab.test.com/api/v4/https://gitlab.test.com/api/v4/projects/21/merge_requests/15851/pipelines?id=21&merge_request_iid=15851&page=2&per_page=20',
        status: 404,
        statusText: 'Not Found',
        headers: [Object],
        counter: 0 } },
  description: '404 Not Found' }

Notice the "https://gitlab.test.com/api/v4/https://gitlab.test.com/api/v4/" of the URL

**Steps to reproduce**

Simply call MergeRequests.pipelines().

**Expected behaviour**
Pipelines are returned.

**Actual behaviour**
404 error due to invalid URL

**Possible fixes**
The API host value is being inserted into the request URL twice.

**Comment by scottboyd-ai** [comment]
This appears to be a problem on a number of functions including MergeRequest.commits() and Commits.show().

**Comment by jdalrymple** [comment]
#353 related

**Comment by scottboyd-ai** [comment]
I'm still experiencing this issue on 6.3.6.

**Comment by jdalrymple** [comment]
Lol see #354

**Comment by jdalrymple** [comment]
-

**Comment by casz** [comment]
Hopefully, 6.3.7 should fix your issue @scottboyd-ai

**Comment by scottboyd-ai** [comment]
Looks great! You guys are the best!
