### ISSUE TITLE
Add missing endpoints for Deploy Keys

### ISSUE THREAD

**Issue by mayorova** [jdalrymple/node-gitlab#373]
**Description**
Current implementation of the [DeployKeys](https://github.com/jdalrymple/node-gitlab/blob/da1a8f6/src/services/DeployKeys.ts) doesn't include some endpoints:

Here is the mapping with the current GitLab API documentation:

node-gitlab | GitLab API | Documentation
------------ | ------------- | -------------
`.add` | `POST /projects/:id/deploy_keys` | [Add deploy key](https://docs.gitlab.com/ee/api/deploy_keys.html#add-deploy-key)
`.all` | `GET /projects/:id/deploy_keys` | [List project deploy keys](https://docs.gitlab.com/ee/api/deploy_keys.html#list-project-deploy-keys)
`.show.` | `GET /projects/:id/deploy_keys/:key_id` | [Single deploy key](https://docs.gitlab.com/ee/api/deploy_keys.html#single-deploy-key)
`.enable` | `POST /projects/:id/deploy_keys/:key_id/enable` | [Enable a deploy key](https://docs.gitlab.com/ee/api/deploy_keys.html#enable-a-deploy-key)
**-missing-** | `PUT /projects/:id/deploy_keys/:key_id` | [Update deploy key](https://docs.gitlab.com/ee/api/deploy_keys.html#update-deploy-key)
**-missing-** | `DELETE /projects/:id/deploy_keys/:key_id` | [Delete deploy key](https://docs.gitlab.com/ee/api/deploy_keys.html#delete-deploy-key)
**-missing-** | `GET /deploy_keys` | [List all deploy keys](https://docs.gitlab.com/ee/api/deploy_keys.html#list-all-deploy-keys)

**Proposal**
While `PUT` and `DELETE` endpoints can easily be implemented by adding `.edit` and `.remove` method, I am not sure how to tackle `GET /deploy_keys` (not scoped by project), without introducing a breaking change.
Maybe allow having a null `projectId` in `.all`? Or having a different method for this global scope?

**Comment by jdalrymple** [comment]
This is a well formatted issue <3. Ill fix this asap

**Comment by jdalrymple** [comment]
Not to worried about the breaking change, that's the benefit of them semver numbers.

**Comment by jdalrymple** [comment]
Give the PR a look to make sure I didnt overlook something! :D

**Comment by mayorova** [comment]
@jdalrymple Wow, that was a fast fix! 🚀 Thank you so much!

I am not too familiar with TypeScript, but it looks good to me! 🙂

**Comment by jdalrymple** [comment]
Build has been fixed, and released with 7.0.1 :)

**Comment by mayorova** [comment]
Awesome, thanks a lot @jdalrymple !
