### ISSUE TITLE
Push rules

### ISSUE THREAD

**Issue by checkmatez** [jdalrymple/node-gitlab#374]
**Description**
Not sure if it already implemented, but I wasn't able to find - how to create push-rules via API? https://gitlab.com/gitlab-org/gitlab-ee/merge_requests/2367

**Proposal**
Add PushRules namespace.

**Comment by jdalrymple** [comment]
https://github.com/jdalrymple/node-gitlab/blob/master/src/services/PushRule.ts

Though it should be pluralized. Oops, will fix that in a future release.

**Comment by checkmatez** [comment]
Oh, I guess it is not yet released?

**Comment by jdalrymple** [comment]
Hmm no it should be released :s?

**Comment by jdalrymple** [comment]
It was missing from the project bundle and the README. Fixing it now!
