### ISSUE TITLE
TypeError: global$1.XMLHttpRequest is not a constructor

### ISSUE THREAD

**Issue by fullstackwebdev** [jdalrymple/node-gitlab#377]
**Description**

I am unable to get a basic example to work.

I then decided to just open up 'node' on my shell and try to import Gitlab, I got an error
see below:

Also the examples on the readme.MD do not work -- there are invalid syntax errors ("=" where it should be ":") and there doesn't seem to be a 'fool proof cut and paste this to check if your env is OK' to get me started.  

**Steps to reproduce**
```
  node
> var Gitlab = require('gitlab')
Thrown:
TypeError: global$1.XMLHttpRequest is not a constructor
    at checkTypeSupport (/home/fullstack/dev/fullstack/gitlab-api/node_modules/gitlab/dist/index.js:1:31955)
    at Object.<anonymous> (/home/fullstack/dev/fullstack/gitlab-api/node_modules/gitlab/dist/index.js:1:32279)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:827:10)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)
> 
```

it should load the module

**Expected behaviour**

**Actual behaviour**

It does not load the module

**Possible fixes**

Something seems to be very wrong

**Comment by nromanen** [comment]
The same issue occurs for me

**Comment by jdalrymple** [comment]
Very very  weird. I'll look into this today. Which version of the library are you guys using ?

**Comment by nromanen** [comment]
7..0.0

**Comment by jdalrymple** [comment]
So odd since the xml file has been removed months ago...

**Comment by jdalrymple** [comment]
Seems to be due to the addition of the https Agent. Looking into how to work around it.

**Comment by casz** [comment]
Just say no to allowing to connect to unsecure sites... it is not that hard to import a certificate

**Comment by jdalrymple** [comment]
I mean that's one way forward. It's just frustrating because node fetch does support it, but for some reason the packing with rollup returns a package with this error. Almost like the polyfill is missing.

**Comment by gdelory** [comment]
Just wanted to add that the problem appeared for me when upgrading from 6.3 to 6.4, and was still there with 7.0. So I assumed this was introduced with 6.4, just in case that helps.

**Comment by jdalrymple** [comment]
Yup it was due to the introduction of the https Agent class

**Comment by jdalrymple** [comment]
Give it a check now! :D

**Comment by gdelory** [comment]
7.0.1 works fine, thanks!

**Comment by fbartho** [comment]
Starting this afternoon, I started getting this issue when using DangerJS https://github.com/danger/danger-js/issues/1012

Is there something recent that might have caused this to reappear?

**Comment by jdalrymple** [comment]
> 
> 
> Starting this afternoon, I started getting this issue when using DangerJS [danger/danger-js#1012](https://github.com/danger/danger-js/issues/1012)
> 
> Is there something recent that might have caused this to reappear?

Seems odd, nothing has changed recently. What version are you using?

**Comment by fbartho** [comment]
The branch was a relatively long running branch to upgrade a ton of dependencies (react-native 0.62), and this was the first build out of it, so I suspect that we somehow have a mismatch in something there. Will update this after further investigation
