### ISSUE TITLE
Process hanging when using async/await with ProjectsApi or TagsApi

### ISSUE THREAD

**Issue by tiger-seo** [jdalrymple/node-gitlab#386]
**Description**

Data from response is returned and then process is hanging until time out as defined in requestTimeout when using async/await with Projects and Tags apis. This problem was in the v5.0.2 and it exists in the v8.0.0.

**Steps to reproduce**

```typescript
import { Gitlab, Tags } from 'gitlab';

class GitlabService2 {

    private getGitlabApi() {
        const gitlabConfig = { host: 'gitlab.company.org', token: 'token' };

        return new Gitlab({
            host: `https://${gitlabConfig.host}`,
            requestTimeout: 10000,
            token: gitlabConfig.token
        });
    }

    public getTagsApi(): Tags {
        return this.getGitlabApi().Tags;
    }

    public async findTags() {
        return this.getTagsApi().all(91);
    }

}

const gitlabService = new GitlabService2();
setTimeout(async () => {
    const tags = (await gitlabService.findTags()) as {name: string}[];
    tags.forEach(t => console.info(t.name));
});
```

// The code above is reproducing the problem

**Expected behaviour**

No hang, but immediate process terminate after data return.

**Actual behaviour**

Data returned and then process is hanging time defined in requestTimeout and only after that the process is terminated.

**Possible fixes**
Have no idea.

**Comment by jdalrymple** [comment]
#348
