### ISSUE TITLE
How do I close the connection or clean up in general

### ISSUE THREAD

**Issue by pkaske** [jdalrymple/node-gitlab#394]
**Description**

I'm coding a cli tool with commander.js and in one of my command I use `RepositoryFiles.showRaw` to download the contents of a file. I noticed that the cli tool won't exit but stay running as soon as I use a gitlab api call. Is there a way to cleanup to make the cli exit after the api call is finished?

**Steps to reproduce**

```js
const cli = require('commander');
const { Gitlab } = require('gitlab');

cli.command('download')
  .action(async () => {
    const api = this.api = new Gitlab({
      host: 'https://mygitlabhost/',
      token: 'TOKEN',
    });

    const pkgContent = await api.RepositoryFiles.showRaw('123', '/package.json', 'master');
    console.log(pkgContent);
  });

cli.parse(process.argv);
```

Then run it with `node . download` you will notice that the script wont exit.

**Expected behaviour**
The script should show the contents of package.json and exit.

**Actual behaviour**
It shows the file contents as expected but stays alive.

**Possible fixes**
Maybe there stays a http connection open to the server that needs to be closed somehow?

**Comment by jdalrymple** [comment]
Just waiting for the PR to be merged connected to this issue #348
