### ISSUE TITLE
HELP: How can I get status code returned by Gitlab API?

### ISSUE THREAD

**Issue by pratikjagrut** [jdalrymple/node-gitlab#396]
I want to check whether repo is reachable or not. e.g If I make a get request on gitlab URL and if URL is wrong then it will return an error code like `404 Not found`, but if everything is good it will return status code `200 OK`. So how can I get this status code?

**Comment by jdalrymple** [comment]
Currently it should just throw an error and return an error message in the response. That error that is thrown **should** be the response error which would include the status code.

This is how its handling the call internally:

```
    try {
      response = await Ky(endpoint, requestOptions);
    } catch (e) {
      if (e.response) {
        const output = await e.response.json();

        e.description = output.error || output.message;
      }
      
      throw e;
    }
```

**Comment by pratikjagrut** [comment]
How can I check repo is reachable or not? Can you show me any code snippet or example for it?

**Comment by pratikjagrut** [comment]
And one more issue I'm facing is any method for `client.Branches.all(this.projectID)` is giving me result quickly but taking a too long time to finish the call after I get the result.

**Comment by casz** [comment]
it's basic try catch or promise then catch handling.

**Comment by jdalrymple** [comment]
@pratikjagrut see issue #348 for the timeout bug. Hopefully gonna get that merged today.

**Comment by pratikjagrut** [comment]
@jdalrymple **Kudos** I just tried my code and timeout issue is no more.
