### ISSUE TITLE
missing migration section in docs

### ISSUE THREAD

**Issue by DanielRuf** [jdalrymple/node-gitlab#402]
**Description**
It seems https://github.com/jdalrymple/node-gitlab/blob/master/README.md#migrating-from-node-gitlabnode-gitlab does not exist (anymore).

**Steps to reproduce**
Go to https://github.com/jdalrymple/node-gitlab/blob/master/README.md#migrating-from-node-gitlabnode-gitlab

**Expected behaviour**
There should be a migration guide.

**Actual behaviour**
There is no migration guide.

**Possible fixes**
Either remove the link / reference or add the migration section.

**Comment by jdalrymple** [comment]
Oops i missed removing the reference!

**Comment by hanselke** [comment]
hi,
the migration docs seem to be missing again

**Comment by jdalrymple** [comment]
> Oops i missed removing the reference!

Since its been such a long time since the package was updated. I removed the reference to the migration guide. Is there something youre having trouble with?

**Comment by hanselke** [comment]
for some reason, the new library is hitting 127.0.0.1 instead of my supplied 'host' section... i do not have a GITLAB_HOST env var. the exact code works using the previous library

**Comment by jdalrymple** [comment]
Could you share your code snippet so we can see where it might be causing a problem :) ?

**Comment by hanselke** [comment]
@jdalrymple thanks but i figured out what the issue is. for some reason, it clashes when https://www.npmjs.com/package/cloudflare is imported as well.
