### ISSUE TITLE
Users.session throws 404

### ISSUE THREAD

**Issue by DanielRuf** [jdalrymple/node-gitlab#404]
**Description**
https://github.com/jdalrymple/node-gitlab/blob/226b11f48c1f5041de11d042708df9c3ed229c6a/src/services/Users.ts#L51

`await api.Users.session(user, pass)` throws a 404

https://gitlab.com/api/v4/session

**Steps to reproduce**

**Expected behaviour**

**Actual behaviour**

**Possible fixes**

**Comment by jdalrymple** [comment]
https://gitlab.com/gitlab-org/gitlab-ce/blob/master/CHANGELOG.md#1020-2017-11-22

Apparently the Session API was removed a while back in v 10.2.0. I could add an error message to make that clearer?
