### ISSUE TITLE
Gitlab with Angular 8 (crypto/randomstring)

### ISSUE THREAD

**Issue by 128keaton** [jdalrymple/node-gitlab#407]
**Description**
I am unable to use the `node-gitlab` npm package in my Angular 8 project since, during compiliation, it complains about missing the `crypto` module (referenced from the `randomstring` module required by `node-gitlab`:

```
ERROR in ./node_modules/randomstring/lib/randomstring.js
Module not found: Error: Can't resolve 'crypto' in
'C:\angular\project-angular\node_modules\randomstring\lib'
```

1. Install the Gitlab npm package in an Angular project `npm i --save gitlab`
2. Attempt to build the Angular project `ng build` (or `ng serve`)

**Expected behaviour**

The project should build (or be served) and work properly.

**Actual behaviour**
*Full output of `ng build`:*

```
C:\angular\project-angular\mojo-angular>ng build

Date: 2019-08-07T16:04:48.426Z
Hash: 637284f03474ee15c016
Time: 20198ms
chunk {main} main-es5.js, main-es5.js.map (main) 854 kB [initial] [rendered]
chunk {polyfills} polyfills-es5.js, polyfills-es5.js.map (polyfills) 632 kB [initial] [rendered]
chunk {runtime} runtime-es5.js, runtime-es5.js.map (runtime) 6.09 kB [entry] [rendered]
chunk {scripts} scripts.js, scripts.js.map (scripts) 585 kB [entry] [rendered]
chunk {styles} styles-es5.js, styles-es5.js.map (styles) 449 kB [initial] [rendered]
chunk {vendor} vendor-es5.js, vendor-es5.js.map (vendor) 9.74 MB [initial] [rendered]

ERROR in ./node_modules/randomstring/lib/randomstring.js
Module not found: Error:
Can't resolve 'crypto' in 'C:\angular\project-angular\node_modules\randomstring\lib'
```

**Other information:**
* node version - v10.16.0
* @angular/core version  - 8.1.1
* OS - Windows 10 Enterprise (OS Build 17763.615)

**Comment by 128keaton** [comment]
Well, I actually found a workaround, but I'm not happy about it.

I had to add the following to my `package.json`:
```json
"browser": {
    "fs": false,
    "path": false,
    "os": false,
    "crypto": false,
    "stream": false,
    "http": false,
    "tls": false,
    "zlib": false,
    "https": false,
    "net": false
},
```

Then, to fix the next issue, I added the following to my `src/polyfills.ts`:
```js 
(window as any).global = window;
```

Is this actually fixable without this workaround (I guess without the global crypto module?)

**Comment by jdalrymple** [comment]
I could try replacing randomstring with something internal?

**Comment by 128keaton** [comment]
@jdalrymple right... this is why I was hesitant to actually open an issue in the first place. What about using something like https://www.npmjs.com/package/docker-names? 

Looks like you're just creating default project filename metadata:

https://github.com/jdalrymple/node-gitlab/blob/3e77d07f5421dac65814995e474ab747ea9b6c91/src/services/Projects.ts#L139

https://github.com/jdalrymple/node-gitlab/blob/3e77d07f5421dac65814995e474ab747ea9b6c91/src/services/ProjectImportExport.ts#L23

**Comment by jdalrymple** [comment]
Works for me. The user reallllly should pass a filename, so anything generated should be fine :)

**Comment by jdalrymple** [comment]
Actually, may be better just to use a timestamp no?

**Comment by 128keaton** [comment]
@jdalrymple Actually, yes, that makes the most sense (literally what base random is anyway, ha!). I'll fork and open a PR later today. Thanks!
