### ISSUE TITLE
Support creating fork relationships

### ISSUE THREAD

**Issue by Charuru** [jdalrymple/node-gitlab#410]
Fork relationship described here:
https://docs.gitlab.com/ce/api/projects.html#fork-relationship

**Steps to reproduce**

`  api.Projects.fork(65, 66)
`

**Expected behaviour**

A new fork relationship is created between 65 and 66.

**Actual behaviour**

Tries to fork 65.

**Comment by jdalrymple** [comment]
api.Projects.fork only supports forking projects at the moment, not forking relationships :) Will add soon!
