### ISSUE TITLE
Why is node 12 required?

### ISSUE THREAD

**Issue by alfaproject** [jdalrymple/node-gitlab#422]
Renovate just attempted to update our `gitlab` dependency and the pipeline is failing with

```
yarn install v1.17.3
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
warning Resolution field "@types/node@10.14.16" is incompatible with requested version "@types/node@^12.0.2"
warning Resolution field "aws-sdk@2.437.0" is incompatible with requested version "aws-sdk@^2.509.0"
[3/5] 🚚  Fetching packages...
error gitlab@10.2.0: The engine "node" is incompatible with this module. Expected version ">=12.0.0". Got "10.15.3"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

We are a Serverless company and are using AWS Lambda with node 10 runtime, therefore we'd like our local environment to use node 10 at the most.

Is there any hard requirement for the `gitlab` module to really need node 12?

**Comment by casz** [comment]
Send a pull request 😬

**Comment by alfaproject** [comment]
@casz fair enough: https://github.com/jdalrymple/node-gitlab/pull/423

**Comment by alfaproject** [comment]
This has not been fixed with https://github.com/jdalrymple/node-gitlab/commit/049bebca71f7fa5e4acf703b292c3a3a80adf107

Thank you @jdalrymple (:
