### ISSUE TITLE
PushRules.show() throws error when there are no push rules on a new project

### ISSUE THREAD

**Issue by krische** [jdalrymple/node-gitlab#426]
**Description**
When running PushRules.show() on a newly created project without push rules, an error is thrown: `TypeError: Cannot read property 'length' of null`

This is because GitLab itself just returns `null` when a project doesn't have any push rules defined, but the `null` value is not being detected and handled properly.

**Steps to reproduce**
1. Create a new project in GitLab.
2. Run `PushRules.show()` on this new GitLab project.
3. node-gitlab will throw an error

**Expected behaviour**
The `PushRules.show()` should probably return `null` as well.

**Actual behaviour**
Error

**Possible fixes**
Perhaps `RequestHelper.get()` should have a null check somewhere and skip all the pagination stuff if the body is null.

**Comment by krische** [comment]
Yes, I just tried on 11.0.0 and still receive error:
```
TypeError: Cannot read property 'length' of null
    at /node_modules/gitlab/dist/index.js:1:3949
    at /node_modules/gitlab/dist/index.js:1:2514
    at Object.next (/node_modules/gitlab/dist/index.js:1:2619)
    at p (/node_modules/gitlab/dist/index.js:1:1380)
```

**Comment by krische** [comment]
My guess is it [RequestHelper Line 56](https://github.com/jdalrymple/node-gitlab/blob/master/src/infrastructure/RequestHelper.ts#L56):
```ts
return (query.page || body.length > 0) && showPagination ? { data: body, pagination } : body;
```

If `body` is null, which it is in this case, then `body.length` would throw that error.

**Comment by jdalrymple** [comment]
Weird, not sure how its ever null though. here:

https://github.com/jdalrymple/node-gitlab/blob/master/src/infrastructure/KyRequester.ts#L51

We set a default value :/

**Comment by jdalrymple** [comment]
AH, nevermind, that sets a default for the response, not the body

**Comment by krische** [comment]
Thanks! This whole thing really seems like more of an issue with GitLab. They should be returning an empty object or something if there are no push rules defined, not `null`.

But I guess their current behavior is their current behavior, and thus this library should support it 😄

**Comment by jdalrymple** [comment]
Weird, creating a new project through Gitlab assigns default push rules

**Comment by jdalrymple** [comment]
Im guessing that the null response doesnt have a json content type. Which would assign it a text value, which would be null thus causing the problem. I've now set a default text value, well see if that solves the problem correctly.

**Comment by jdalrymple** [comment]
One more time @krische , Still getting the error with the latest version? 😂

**Comment by krische** [comment]
It works!

**Comment by krische** [comment]
I was wrong, it looks like this issue still occurs.

If I look at the raw response returned by GitLab for `/api/v4/projects/<id>/push_rule` when there are no push rules configured (new project); it still returns Content-Type `application/json` with a body of just `null`.

So it looks like you still need to add a null check for `body` at [this line](https://github.com/jdalrymple/node-gitlab/blob/master/src/core/infrastructure/RequestHelper.ts#L56) before you try to read `body.length`.

**Comment by jdalrymple** [comment]
I found the problem. The helper functions for .json or .text etc are async. So I'm not waiting for their response before checking for a null, causing it to never use the defaulted logic.

**Comment by jdalrymple** [comment]
Just pushed a fix!
