### ISSUE TITLE
Somehow figure out when the GL instance is 100% up and running before running tests

### ISSUE THREAD

**Issue by jdalrymple** [jdalrymple/node-gitlab#428]
**Description**

Currently the tests wait a specified amount of time before beginning after starting up the gitlab instance. This is needed because a key needs to be generated before any of those tests can run. To create this token, we make an API request to the GL instance and if the instance isnt up, the token remains null and subsequently fails all the tests. 

Not only is this inefficient but prone to error if the instance isn't up in that allotted time. In the past we tried to figure this out based on the docker up time endpoints ([liveliness and readiness](https://docs.gitlab.com/ee/user/admin_area/monitoring/health_check.html)) but they didnt help, at least not a year ago. I would love to fix this and avoid erroneous failed builds :upside_down_face: 

**Steps to reproduce**
Run the integration tests, but have the execute without a time delay. 

**Expected behaviour**
Tests wait until GL instance is ready before running

**Actual behaviour**
Using a fixed time delay before executing

**Possible fixes**
Maybe readiness works now? Or perhaps changing the Gitlab runner container such that these endpoints actually work as they should?

**Comment by casz** [comment]
Maybe we can create a specific docker container for it?

You could add a simple nodejs container sidecar that you repeat attempting to login unless you get 200?

Perhaps look into: https://github.com/testcontainers/testcontainers-node

**Comment by casz** [comment]
For your testing I would properly switch to https://github.com/testcontainers/testcontainers-node it can even do await successful response

**Comment by casz** [comment]
Ya but you want a second container or some code that waits.
Does a login and starts navigating to health_check or the first project to ensure that the gitlab container is ready.

So wait till port `80` and `433` respond then attempt login and keep repeating till you get logged in.
Then head to first project and keep trying till get a `200` respond.
You could go further and have code that attempts to create a issue and wait till it successfully manages to.

**Comment by casz** [comment]
Well one will help prove the second? 😆

**Comment by casz** [comment]
That could work too :)
