### ISSUE TITLE
Make my function chose between update and create in Google Cloud Functions

### ISSUE THREAD

**Issue by Musicalink** [jdalrymple/node-gitlab#437]
Hi,

I currently need to make my cloud function choose between updating or creating file in a commit but after some hours of search, I still can't find how to check if the file exist.

The code is in a Google Cloud Function and is written in Nodejs 8 !

Thank you !

**Comment by jdalrymple** [comment]
Hi! Not sure i follow exactly. "updating or creating file in a commit" ? Could you explain further?
