### ISSUE TITLE
Mirroring project on gitlab.com

### ISSUE THREAD

**Issue by arsdehnel** [jdalrymple/node-gitlab#440]
**Description**

Mirror this project onto gitlab.com using GitLab's [provided mirroring](https://docs.gitlab.com/ee/workflow/repository_mirroring.html#pulling-from-a-remote-repository-starter).  

**Possible solutions**

It seems _easiest_ to have gitlab.com pull this repo over to a matching gitlab.com group but that's only free until March 22, 2020.  So we could do that and then switch to a `push` model at that time or we can just change to gitlab.com as the source now and have it push to github.  Given the massive difference in usage between github and gitlab it's weird to switch but it's also a little weird to have the gitlab API managed within github.  

I guess I'd suggest we move code to gitlab.com and mirror it to github for visibility.  Maintain everything code-related within gitlab.  

**Additional Consideration 1: Tech Debt**

The issue with moving code to gitlab is that then CI, Issues and any bots would have to go with it.  The ability for tools to hook into gitlab is a much narrower list than those for github so I'd be concerned some of your automation and bots would break.  Not knowing all of what you have wired up it's hard for me to know for sure.  Maybe they are all built off webhooks in which case we're probably alright aside from the work to make them switch over.

**Additional Consideration 2: Naming**

Would you want to move this over to your personal namespace in gitlab or would it be under some node-gitlab group?  Not opposed to just using your namespace, just thought I'd bring it up in case you want to separate your own personal stuff from it for some reason.

**Comment by casz** [comment]
@jdalrymple Please do not move this repo to GitLab.

GitHub actions will be generally available as of November 13 making it easy to have publishing of GitHub pages or publishing to NPM or whatever automated workflow you desire.

Deploy pages action
https://github.com/JamesIves/github-pages-deploy-action

List of awesome actions
https://github.com/sdras/awesome-actions

See my GitHub actions usage here
https://github.com/casz/express-ipfilter/tree/master/.github/workflows

Also GitLab as you said for groups will not be free after March 22, 2020.
Where GitHub will stay free for open source.

GitLab has yet to fix code search, proper notifications, traffic insights for repo, or pulse for repo

https://github.com/jdalrymple/node-gitlab/graphs/traffic
https://github.com/jdalrymple/node-gitlab/pulse/monthly

Plenty of other features that GitLab lacks.

**Comment by jdalrymple** [comment]
Hmm, I understand both sides of the argument. Its almost the same argument Gitlab has to make when their original repo was on Github. It should be mirrored either way though, since alot of people do initially look in Gitlab assuming the wrapper would be available there.

**Comment by arsdehnel** [comment]
I feel like my OP was pretty opinionated when I am not that strongly opinionated on it. Could we mirror to gitlab with github still being the source of record and use gitlab pages for a couple months until github actions can solve the pages problem?  Then we will have the visibility of the code on gitlab.com while also allowing us to separate out the pages stuff to be in a "CI-like" environment (GitLab CI for 2 months and then GitHub Actions)?

**Comment by jdalrymple** [comment]
That works for me! I can setup the mirror this week

**Comment by jdalrymple** [comment]
Its been mirrored :) same url on gitlab: https://gitlab.com/jdalrymple/node-gitlab

**Comment by casz** [comment]
FYI about github pages. GitHub can auto deploy based on what's in master branch or in the master branch docs folder

**Comment by jdalrymple** [comment]
Im gonna close this one, in favour of the documentation case for the current work being done in the PR
