### ISSUE TITLE
How to fetch + merge?

### ISSUE THREAD

**Issue by digimbyte** [jdalrymple/node-gitlab#444]
I've been up and down the documentation, trying a few things but I can't seem to do a project pull request.
am I missing something or is this more for managing the git project remotely?

Thanks

**Comment by jdalrymple** [comment]
What are you trying to do exactly? Create a PR on Gitlab?

**Comment by digimbyte** [comment]
I am looking at creating a node.js app that self updates every week or via external command

**Comment by jdalrymple** [comment]
updates what though? Do you want the local repo to update your girlab repo on the server (ie gitlab.com)?

**Comment by digimbyte** [comment]
I want the local repo to update itself from the server. so I don't need to use 'git pull' all the time

**Comment by jdalrymple** [comment]
This library doesn't provide git interactions, just a wrapper around the GitLab API :(

**Comment by jdalrymple** [comment]
Though you could probably add a url to the gitlab system hooks, and handle the incoming webhook to then run git pull in that repo? You wouldnt need this library though for that.
