### ISSUE TITLE
how to use ProjectImportExport.download?

### ISSUE THREAD

**Issue by buonzz** [jdalrymple/node-gitlab#447]
DISCLAIMER: this is more of me confused on how to the use library, sorry in advance if this might be a really stupid question :(

**Description**

Im trying to bulk export/download a bunch of repos
by calling this method https://github.com/jdalrymple/node-gitlab/blob/master/src/core/services/ProjectImportExport.ts#L6-L10

here is my code
```
...
    const api = new Gitlab({
      token: Env.get('GITLAB_ACCESS_TOKEN', ''),
      host: Env.get('GITLAB_URL', '')
    });
....
// projects is stuff i pulled from database
    projects_array.forEach(async (project) => {
            const db_project = await Project.find(project.id)
            try{
              await api.ProjectImportExport.download(project.gitlab_id)
              this.info(project.path_with_namespace + ' download initiated')
              db_project.export_status = 'download initiated'
            }
            catch(e){
                db_project.export_status = 'error during download'
                this.warn('unable to download project ' + project.path_with_namespace + "(" + project.gitlab_id + ")" )
            }

            await db_project.save()
      }) // foreach
```

**Steps to reproduce**
just instantiate an api, then call this
`await api.ProjectImportExport.download(<a valid gitlab project id>)`

**Expected behaviour**
i was expecting to be able to pass the local path (folder or absolute filename) where it will download the tar.gz file

**Actual behaviour**
it just calls the method, but it doesnt download anything neither in local directory or anywhere else

**Possible fixes**
was there any parameter i need  to pass, or how should this be used supposedly?

**Comment by jdalrymple** [comment]
Hmm that should work! Ill check it out today!

**Comment by jdalrymple** [comment]
There was a bug in the logic but has since been fixed. So do what you're trying to accomplish, you have to 1. schedule an export, then 2. download it. Otherwise there will be nothing to download.

```
 await api.ProjectImportExport.schedule(project.gitlab_id)
 await api.ProjectImportExport.download(project.gitlab_id)
```
