### ISSUE TITLE
Support project and group labels api

### ISSUE THREAD

**Issue by hanselke** [jdalrymple/node-gitlab#454]
Library currently doesnt support project or group labels api.

**Comment by casz** [comment]
Feel free to contribute, it is [hacktoberfest](https://hacktoberfest.digitalocean.com) after all 😄

**Comment by casz** [comment]
Library does support project level however: https://github.com/jdalrymple/node-gitlab/blob/b0ee51767d6dfbf3fcae9ff1c1c32c8e4c67641c/src/core/services/Labels.ts

It should properly follow the resource pattern though
https://github.com/jdalrymple/node-gitlab/blob/b0ee51767d6dfbf3fcae9ff1c1c32c8e4c67641c/src/core/templates/ResourceMembers.ts
https://github.com/jdalrymple/node-gitlab/blob/b0ee51767d6dfbf3fcae9ff1c1c32c8e4c67641c/src/core/services/GroupMembers.ts

**Comment by jdalrymple** [comment]
Yea it would probably be better to implement something similar to the resource template, and then use that for the project and group labels :)
