### ISSUE TITLE
Retrieving events

### ISSUE THREAD

**Issue by xtr3me** [jdalrymple/node-gitlab#61]
When trying to retrieve all events from a project via the new Event service i came across the following difference between this package and the gitlab api:

https://docs.gitlab.com/ee/api/events.html#list-a-project-39-s-visible-events
The API states that: action and targetType are optional yet this package makes them mandatory as seen in: https://github.com/jdalrymple/node-gitlab-api/blob/4e78749edcd6022736cb8c0471df008de2fc3d19/src/services/Events.js#L27

This prevents me from using the Events service as i cant retrieve all the events.

(ps. i'm only interested in pushed events on the project, but i get an empty response when using:
 { action: 'pushed', targetType: 'project' }, that's how i found the difference between the API and the Service)
(ps2. how can i see the complete response and not only the parsed response for debugging purposes)

**Comment by jdalrymple** [comment]
Must of missed that! Hmm right now the full responses are hidden for clarity, but maybe adding a debug option to expose those would be helpful

**Comment by xtr3me** [comment]
I can make a PR, do you want to remove the validateEventOptions all together or do you have a different idea about that?

**Comment by jdalrymple** [comment]
Fixing it now :)

**Comment by jdalrymple** [comment]
Should be fixed now!

**Comment by hsablonniere** [comment]
Hey @jdalrymple ;-)

In 4.2.2, the `action` and `target` are still required:
https://github.com/jdalrymple/node-gitlab/blob/4.2.2/src/services/Events.ts#L32-L36

I would like to list all events with `after` and `before` but without any types...

**Comment by jdalrymple** [comment]
Oh man, sorry :( Ill look soon

**Comment by jdalrymple** [comment]
Just released to npm and the next build!

**Comment by jdalrymple** [comment]
Oops! One moment!
