### ISSUE TITLE
Feature-Request: Obey the GitLab rate limit

### ISSUE THREAD

**Issue by max-wittig** [jdalrymple/node-gitlab#73]
This feature is not really documented by GitLab, but causes GitLab to send 429 (Too many requests), when enabled or set to low.
It specifies the time the client needs to wait with the [Retry-After header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) in seconds.

GitLab lacks documentation about this feature, but rate-limits can be set in the Admin UI (see screenshot)
and via the settings API.
![image](https://user-images.githubusercontent.com/6639323/38921537-4fb45bdc-42f6-11e8-8bf1-397dff48c7a4.png)

```json
{
 "throttle_authenticated_api_enabled": false,
 "throttle_authenticated_api_requests_per_period": 2,
 "throttle_authenticated_api_period_in_seconds": 10,
}
```

`node-gitlab-api` should obey these limits. Wait (sleep) the specified time if HTTP 429 is received and retry the request.

**Comment by jdalrymple** [comment]
Havent gotten around to this as of yet, but i will soon! Want to finish off the basic testing issue first.

**Comment by jdalrymple** [comment]
Finally had a moment to look deeper into this. Still trying to figure out the best way to handle it. I could:

1. Look up the users configuration on init of a API Service and then set it for that service
2. Same as 1, but figure out a way to set it globally so if the user inits 10 services, the request for the config doesn't happen 10 times
3. ... not sure lol :P

Besides getting and storing the config, actually implementing it isnt too bad!

**Comment by max-wittig** [comment]
@jdalrymple [I've implemented it for python-gitlab](https://github.com/python-gitlab/python-gitlab/pull/488).

I've found that you can just wait, as long as your GitLab instance specifies. 
It will send a [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) header.
along with the 429 HTTP Error Code (Too many request).

So best way would be to have the main request handler wait for x-seconds, **if** 429 is send.

**Comment by jdalrymple** [comment]
Wicked, I'll try that

**Comment by max-wittig** [comment]
This may need to be fixed in the request library, that is used.

https://github.com/request/request

**Comment by max-wittig** [comment]
@jdalrymple Awesome thanks!
