### ISSUE TITLE
Settle on official node gitlab library location

### ISSUE THREAD

**Issue by MunifTanjim** [jdalrymple/node-gitlab#78]
This library is now available as `gitlab` npm package. But the README file has outdated information about that.

Also, about the [node-gitlab/node-gitlab](https://github.com/node-gitlab/node-gitlab) repository, one of the following should be done:

- Transfer `jdalrymple/node-gitlab-api` to `node-gitlab/node-gitlab`
- Archive `node-gitlab/node-gitlab` repository. Mark it as deprecated in its README and point to `jdalrymple/node-gitlab-api`.
- Delete `node-gitlab/node-gitlab` and redirect it's url to `jdalrymple/node-gitlab-api`.

**Comment by jdalrymple** [comment]
https://github.com/node-gitlab/node-gitlab/issues/191

Still trying to come to a conclusion about the libraries, but ill update the readme in the meantime!

**Comment by MunifTanjim** [comment]
I read that issue earlier.

> Not sure what to do about the source code repo, the node-gitlab group is a lil outdated with the most recent thing being since 2015 :(. I could rename the node-gitlab-api repo if it would make it easier to understand?

Still, transferring `jdalrymple/node-gitlab-api` to `node-gitlab/node-gitlab` seems like a good idea. As that repository is already featured in the GitLab docs: https://about.gitlab.com/applications/#api-clients.

**Comment by jdalrymple** [comment]
Updated the repo name for clarity
