### ISSUE TITLE
Project.all() with options is timing out

### ISSUE THREAD

**Issue by imraazrally** [jdalrymple/node-gitlab#82]
After migrating from node-gitlab-api `2.2.8` to `3.0.2`. The following code is timing out
```
        const options = { membership: true, page: 1, per_page: 1 }
        const projects = await client.Projects.all(options);            
```

Any idea why?  from analyzing the debug mode for `request-promise` library it seems that the library is making retry calls even after a succesful response. It continues retry infinitely until my AWS lambda functions timeout.

**Comment by jdalrymple** [comment]
Yikes, that's no good. I'll give it a look asap

**Comment by imraazrally** [comment]
Thanks!
