### ISSUE TITLE
Search.all() url problem

### ISSUE THREAD

**Issue by LogansUA** [jdalrymple/node-gitlab#83]
Hello. I'm trying to use search API. Here's my example:

```javascript
const GitLab = require('node-gitlab-api').default;

const gitlabInstance = new GitLab({
    url: 'http://gitlab.com',
    token: process.env.GITLAB_TOKEN,
});

gitlabInstance.Search.all('project', 'json')
    .then(console.log)
    .catch(console.log);
```

In result i receive an error which contains
```javascript
body: { error: '404 Not Found' } 
```

The reason, I think, in the path which equals: `path: '/api/v4/undefinedsearch?scope=project&search=json'`

Here's the options of request i get:
```
options:
   { url: 'http://gitlab.com/api/v4/undefinedsearch',
     headers: { 'private-token': '%my_private_token%' },
     json: true,
     qs: { scope: 'project', search: 'json' },
     resolveWithFullResponse: true,
     method: 'GET',
     callback: [Function: RP$callback],
     transform: undefined,
     simple: true,
     transform2xxOnly: false },
```

Versions:
```
node@10.1.0
node-gitlab-api@3.0.2
```

Thank you :)

**Comment by imraazrally** [comment]
@LogansUA try `https://gitlab.com`

**Comment by imraazrally** [comment]
hey, the `undefinedSearch` is because when there is no `groupId` or `projectId` defined. It looks like the `else` statement is missing [here](https://github.com/jdalrymple/node-gitlab-api/blob/master/src/services/Search.js#L12).

**Comment by LogansUA** [comment]
Great, will somebody fix it?
