### ISSUE TITLE
Issues with es5 

### ISSUE THREAD

**Issue by imraazrally** [jdalrymple/node-gitlab#84]
Hey, i think i didn't communicate this properly. What i was specifically wondering is when i do a `require('gitlab/dist/es5')` (as opposed to `node-gitlab-api/dist/es5`) i am having issues. This forces me to stick to `node-gitlab-api` of version 3.0.2. but most of the new fixes you put in place such as #82 is only available in `gitlab` library. 

Code:
```
const Gitlab = require('gitlab/dist/es5').default
const client = new Gitlab({
  url:   'https://gitlab.com', // Defaults to http://gitlab.com
  token: 'tG4dZ9UUwijyQKoaZZE2'	// Can be created in your profile.
})
const response = await client.Projects.all({membership: true, page:1, per_page: 1});
``` 

Bug:
```
/Users/irally1/Desktop/test/node_modules/gitlab/dist/es5/infrastructure/XMLHttpRequester.js:18
  return async function (opts) {
               ^^^^^^^^
SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
...
```

Thanks, much appreciated!

**Comment by jdalrymple** [comment]
ill look today!

**Comment by imraazrally** [comment]
Thanks!

**Comment by imraazrally** [comment]
Hey @jdalrymple, wondering if you got a chance to figure out what's happening here? :)

**Comment by jdalrymple** [comment]
Not yet, tried doing last night but then passed out 😪

**Comment by jdalrymple** [comment]
hmm so ive tested with:

node: 9.11.1
npm: 6.0.0
gitlab package: 3.3.2 and it seems to work fine. 

What version of node/npm are you using?

**Comment by imraazrally** [comment]
It’s Node 6.10 (latest node version Lambda supports)

**Comment by imraazrally** [comment]
Hey @jdalrymple, were you able to reproduce this?

**Comment by jdalrymple** [comment]
I was missing a babel conversion for async somewhere. Will publish the fix soon

**Comment by imraazrally** [comment]
@jdalrymple thanks! This is working now! :)
