### ISSUE TITLE
Migrate to TypeScript

### ISSUE THREAD

**Issue by r00ger** [jdalrymple/node-gitlab#89]
Track progress/ideas/questions under this ticket

**Comment by MunifTanjim** [comment]
May I ask what will be the primary benefit of moving the whole codebase to TS?

**Comment by jdalrymple** [comment]
I believe the initial goal was to improve documentation efforts

**Comment by MunifTanjim** [comment]
If we automate the routes generation process, converting the whole codebase to TS won't have much benefit in terms of "improving documentation efforts".

But if this is being done for any other benefits then I've got nothing to say other than, "_TS is really cool_" :smiley:

**Comment by jdalrymple** [comment]
:joy: fair. Either way, trying to focus on tackling one thing at a time.

**Comment by r00ger** [comment]
Hey! Do you have a plan to merge `next` branch to trunk any time soon?

**Comment by jdalrymple** [comment]
Yup! Just waiting until I have the time to test through it all before I release it

**Comment by r00ger** [comment]
@jdalrymple will you please rebase `next` on the latest `master`?

**Comment by jdalrymple** [comment]
Will do today!

**Comment by jdalrymple** [comment]
Going to close this since there is a dup case
